//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ActiveDirectoryContext : DbContext
    {
        public ActiveDirectoryContext()
            : base("name=ActiveDirectoryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<Foundation> Foundations { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Site_Upload> Site_Upload { get; set; }
        public virtual DbSet<parent_employee> parent_employee { get; set; }
        public virtual DbSet<Admin_Module_Found> Admin_Module_Found { get; set; }
        public virtual DbSet<Admin_Module> Admin_Module { get; set; }
        public virtual DbSet<Admin_ModulePage> Admin_ModulePage { get; set; }
        public virtual DbSet<Admin_Page> Admin_Page { get; set; }
        public virtual DbSet<Admin_RoleModule> Admin_RoleModule { get; set; }
        public virtual DbSet<Admin_Users> Admin_Users { get; set; }
        public virtual DbSet<super_admin> super_admin { get; set; }
        public virtual DbSet<EmployeeAndCorrParentEmplName> EmployeeAndCorrParentEmplNames { get; set; }
        public virtual DbSet<EmployeeNames_ParentEmplTable> EmployeeNames_ParentEmplTable { get; set; }
        public virtual DbSet<Employee_Groups> Employee_Groups { get; set; }
    
        public virtual ObjectResult<Foundations_Followup_Result> Foundations_Followup(Nullable<int> foundation_id)
        {
            var foundation_idParameter = foundation_id.HasValue ?
                new ObjectParameter("foundation_id", foundation_id) :
                new ObjectParameter("foundation_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Foundations_Followup_Result>("Foundations_Followup", foundation_idParameter);
        }
    
        public virtual ObjectResult<get_employee_from_Outbox_Visa_Follows_Result> get_employee_from_Outbox_Visa_Follows(Nullable<int> outbox_ID)
        {
            var outbox_IDParameter = outbox_ID.HasValue ?
                new ObjectParameter("Outbox_ID", outbox_ID) :
                new ObjectParameter("Outbox_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_employee_from_Outbox_Visa_Follows_Result>("get_employee_from_Outbox_Visa_Follows", outbox_IDParameter);
        }
    
        public virtual ObjectResult<fill_employee2_Result> fill_employee2(Nullable<int> dept_id)
        {
            var dept_idParameter = dept_id.HasValue ?
                new ObjectParameter("Dept_id", dept_id) :
                new ObjectParameter("Dept_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fill_employee2_Result>("fill_employee2", dept_idParameter);
        }
    
        public virtual ObjectResult<get_org_by_found_Result> get_org_by_found(Nullable<int> found_id)
        {
            var found_idParameter = found_id.HasValue ?
                new ObjectParameter("found_id", found_id) :
                new ObjectParameter("found_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_org_by_found_Result>("get_org_by_found", found_idParameter);
        }
    
        public virtual ObjectResult<get_dept_by_found_Result> get_dept_by_found(Nullable<int> found_id)
        {
            var found_idParameter = found_id.HasValue ?
                new ObjectParameter("found_id", found_id) :
                new ObjectParameter("found_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_dept_by_found_Result>("get_dept_by_found", found_idParameter);
        }
    
        public virtual ObjectResult<get_sub_cat_by_main_cat_Result> get_sub_cat_by_main_cat(Nullable<int> cat_id)
        {
            var cat_idParameter = cat_id.HasValue ?
                new ObjectParameter("cat_id", cat_id) :
                new ObjectParameter("cat_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_sub_cat_by_main_cat_Result>("get_sub_cat_by_main_cat", cat_idParameter);
        }
    
        public virtual ObjectResult<get_Emp_Visa_Follow_Result> get_Emp_Visa_Follow(Nullable<int> commission_ID)
        {
            var commission_IDParameter = commission_ID.HasValue ?
                new ObjectParameter("Commission_ID", commission_ID) :
                new ObjectParameter("Commission_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Emp_Visa_Follow_Result>("get_Emp_Visa_Follow", commission_IDParameter);
        }
    
        public virtual ObjectResult<AdminUsers_SelectName_Exsit_Result> AdminUsers_SelectName_Exsit(string user_name, Nullable<int> iD)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("User_name", user_name) :
                new ObjectParameter("User_name", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminUsers_SelectName_Exsit_Result>("AdminUsers_SelectName_Exsit", user_nameParameter, iDParameter);
        }
    
        public virtual ObjectResult<Admin_Users_Select_Result> Admin_Users_Select(Nullable<int> iD, Nullable<int> foundation_id)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var foundation_idParameter = foundation_id.HasValue ?
                new ObjectParameter("foundation_id", foundation_id) :
                new ObjectParameter("foundation_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_Users_Select_Result>("Admin_Users_Select", iDParameter, foundation_idParameter);
        }
    
        public virtual ObjectResult<SuperAdminUsers_SelectName_Result> SuperAdminUsers_SelectName(string user_name)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("User_name", user_name) :
                new ObjectParameter("User_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuperAdminUsers_SelectName_Result>("SuperAdminUsers_SelectName", user_nameParameter);
        }
    
        public virtual ObjectResult<get_pmp_by_dept> get_pmp_by_dept(Nullable<int> dept_id)
        {
            var dept_idParameter = dept_id.HasValue ?
                new ObjectParameter("dept_id", dept_id) :
                new ObjectParameter("dept_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_pmp_by_dept>("get_pmp_by_dept", dept_idParameter);
        }
    
        public virtual ObjectResult<foundations_selectall> foundations_selectall(Nullable<int> foundation_id)
        {
            var foundation_idParameter = foundation_id.HasValue ?
                new ObjectParameter("foundation_id", foundation_id) :
                new ObjectParameter("foundation_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<foundations_selectall>("foundations_selectall", foundation_idParameter);
        }
    
        public virtual ObjectResult<foundation_check_exist> foundation_check_exist(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<foundation_check_exist>("foundation_check_exist", idParameter, nameParameter);
        }
    }
}
