//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public long Dept_id { get; set; }
        public string Dept_name { get; set; }
        public Nullable<long> Dept_type { get; set; }
        public Nullable<long> Dept_parent_id { get; set; }
        public Nullable<long> Sec_sec_id { get; set; }
        public Nullable<int> foundation_id { get; set; }
    }
}
namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public long PMP_ID { get; set; }
        public Nullable<long> Dept_Dept_id { get; set; }
        public string pmp_name { get; set; }
        public Nullable<long> rol_rol_id { get; set; }
        public string mail { get; set; }
        public Nullable<int> Group_id { get; set; }
        public string english { get; set; }
        public Nullable<long> vacation_mng_pmp_id { get; set; }
        public Nullable<bool> contact_person { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> sec_sec_id { get; set; }
        public string Hire_date { get; set; }
        public string pmp_title { get; set; }
        public string job_no { get; set; }
        public Nullable<int> direct_manager { get; set; }
        public Nullable<int> higher_manager { get; set; }
        public Nullable<int> Report_dept_manage { get; set; }
        public Nullable<int> workstatus { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> university_degree { get; set; }
        public string university_name { get; set; }
        public string major { get; set; }
        public string Token_User_pin { get; set; }
        public Nullable<int> national_id { get; set; }
        public string qualification_date { get; set; }
        public Nullable<int> job_title_id { get; set; }
        public string LastName { get; set; }
        public Nullable<int> foundation_id { get; set; }
    }
}
namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foundation
    {
        public int Foundation_ID { get; set; }
        public string Foundation_Name { get; set; }
        public Nullable<int> code_archiving { get; set; }
        public Nullable<int> Port { get; set; }
        public string Host { get; set; }
        public string UserName_mail { get; set; }
        public string Password { get; set; }
        public string FromAddress { get; set; }
        public string connection_string { get; set; }
        public Nullable<bool> islocal { get; set; }
        public Nullable<int> code_outbox { get; set; }
    }
}
namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public long Org_ID { get; set; }
        public string Org_Desc { get; set; }
        public Nullable<int> New_ID { get; set; }
        public Nullable<int> foundation_id { get; set; }
    }
}
namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent_employee
    {
        public int ID { get; set; }
        public int pmp_id { get; set; }
        public int parent_pmp_id { get; set; }
        public int Type { get; set; }
    }
}
namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Upload
    {
        public int ID { get; set; }
        public string Site_Name { get; set; }
        public string File_Name { get; set; }
        public string File_Ext { get; set; }
        public string logo_file_name { get; set; }
        public string logo_file_Ext { get; set; }
        public byte[] logo_image { get; set; }
        public string e_signature { get; set; }
        public Nullable<int> foundation_id { get; set; }
    }
}
namespace EFModels
{
    using System;
    
    public partial class fill_employee2_Result
    {
        public long PMP_ID { get; set; }
        public string pmp_name { get; set; }
        public Nullable<long> sec_sec_id { get; set; }
    }
}
namespace EFModels
{
    using System;
    
    public partial class Foundations_Followup_Result
    {
        public Nullable<int> Inbox_count { get; set; }
        public Nullable<int> outbox_count { get; set; }
        public Nullable<int> Employee_count { get; set; }
        public string found_name { get; set; }
        public Nullable<int> Visa_count { get; set; }
        public Nullable<int> Follows_count { get; set; }
        public Nullable<int> Visaoutbox_count { get; set; }
        public Nullable<int> Followsoutbox_count { get; set; }
    }
}
namespace EFModels
{
    using System;
    
    public partial class get_dept_by_found_Result
    {
        public long Dept_id { get; set; }
        public string Dept_name { get; set; }
        public Nullable<long> Dept_type { get; set; }
        public Nullable<long> Dept_parent_id { get; set; }
        public Nullable<long> Sec_sec_id { get; set; }
        public Nullable<int> foundation_id { get; set; }
    }
}
namespace EFModels
{
    using System;
    
    public partial class get_employee_from_Outbox_Visa_Follows_Result
    {
        public int Follow_ID { get; set; }
        public string File_name { get; set; }
        public string time_follow { get; set; }
        public Nullable<int> Outbox_ID { get; set; }
        public string Descrption { get; set; }
        public string Date { get; set; }
        public Nullable<int> Visa_Emp_id { get; set; }
        public string pmp_name { get; set; }
    }
}
namespace EFModels
{
    using System;
    
    public partial class get_org_by_found_Result
    {
        public long Org_ID { get; set; }
        public string Org_Desc { get; set; }
    }
}
namespace EFModels
{
    using System;
    
    public partial class get_sub_cat_by_main_cat_Result
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> main_id { get; set; }
    }
}
