//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OutboxContext : DbContext
    {
        public OutboxContext()
            : base("name=OutboxContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Outbox> Outboxes { get; set; }
        public virtual DbSet<Outbox_Main_Categories> Outbox_Main_Categories { get; set; }
        public virtual DbSet<Outbox_Sub_Categories> Outbox_Sub_Categories { get; set; }
        public virtual DbSet<Outbox_Track_Emp> Outbox_Track_Emp { get; set; }
        public virtual DbSet<Outbox_Track_Manager> Outbox_Track_Manager { get; set; }
        public virtual DbSet<Outbox_Visa> Outbox_Visa { get; set; }
        public virtual DbSet<Outbox_Visa_Emp> Outbox_Visa_Emp { get; set; }
        public virtual DbSet<Outbox_Visa_Follows> Outbox_Visa_Follows { get; set; }
        public virtual DbSet<Outbox_follow_emp> Outbox_follow_emp { get; set; }
    
        public virtual int Outbox_cat_save(Nullable<int> outbox_id, Nullable<int> cat_id, Nullable<int> type, Nullable<int> outbox_type)
        {
            var outbox_idParameter = outbox_id.HasValue ?
                new ObjectParameter("Outbox_id", outbox_id) :
                new ObjectParameter("Outbox_id", typeof(int));
    
            var cat_idParameter = cat_id.HasValue ?
                new ObjectParameter("Cat_id", cat_id) :
                new ObjectParameter("Cat_id", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var outbox_typeParameter = outbox_type.HasValue ?
                new ObjectParameter("Outbox_type", outbox_type) :
                new ObjectParameter("Outbox_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_cat_save", outbox_idParameter, cat_idParameter, typeParameter, outbox_typeParameter);
        }
    
        public virtual ObjectResult<outbox_cat_select_Result> outbox_cat_select(Nullable<int> outbox_id, Nullable<int> type)
        {
            var outbox_idParameter = outbox_id.HasValue ?
                new ObjectParameter("Outbox_id", outbox_id) :
                new ObjectParameter("Outbox_id", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<outbox_cat_select_Result>("outbox_cat_select", outbox_idParameter, typeParameter);
        }
    
        public virtual int Outbox_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_Delete", iDParameter);
        }
    
        public virtual ObjectResult<Outbox_DIrect_Relating_Result> Outbox_DIrect_Relating(Nullable<int> related_type, Nullable<int> id)
        {
            var related_typeParameter = related_type.HasValue ?
                new ObjectParameter("related_type", related_type) :
                new ObjectParameter("related_type", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_DIrect_Relating_Result>("Outbox_DIrect_Relating", related_typeParameter, idParameter);
        }
    
        public virtual ObjectResult<Outbox_fillcontrol_Result> Outbox_fillcontrol(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_fillcontrol_Result>("Outbox_fillcontrol", idParameter);
        }
    
        public virtual ObjectResult<Outbox_getorg_Result> Outbox_getorg(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_getorg_Result>("Outbox_getorg", idParameter);
        }
    
        public virtual int Outbox_Save(ObjectParameter iD, Nullable<int> proj_id, Nullable<int> type, Nullable<int> dept_ID, Nullable<int> emp_ID, Nullable<int> org_Id, Nullable<int> group_id, Nullable<int> pmp_pmp_id, Nullable<int> related_Type, Nullable<int> related_Id, Nullable<int> follow_Up_Dept_ID, Nullable<int> dept_Dept_id, Nullable<int> follow_Up_Emp_ID, Nullable<int> status, string subject, string notes, string name, string code, string date, string enter_Date, string org_Name, string org_Out_Box_Code, string org_Out_Box_DT, string paper_No, string paper_Attached, string dept_Desc, string org_Out_Box_Person, Nullable<int> source_Type, string org_Dept_Name, Nullable<int> sub_Cat_id, Nullable<int> finished, Nullable<int> foundation_id)
        {
            var proj_idParameter = proj_id.HasValue ?
                new ObjectParameter("Proj_id", proj_id) :
                new ObjectParameter("Proj_id", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var dept_IDParameter = dept_ID.HasValue ?
                new ObjectParameter("Dept_ID", dept_ID) :
                new ObjectParameter("Dept_ID", typeof(int));
    
            var emp_IDParameter = emp_ID.HasValue ?
                new ObjectParameter("Emp_ID", emp_ID) :
                new ObjectParameter("Emp_ID", typeof(int));
    
            var org_IdParameter = org_Id.HasValue ?
                new ObjectParameter("Org_Id", org_Id) :
                new ObjectParameter("Org_Id", typeof(int));
    
            var group_idParameter = group_id.HasValue ?
                new ObjectParameter("Group_id", group_id) :
                new ObjectParameter("Group_id", typeof(int));
    
            var pmp_pmp_idParameter = pmp_pmp_id.HasValue ?
                new ObjectParameter("pmp_pmp_id", pmp_pmp_id) :
                new ObjectParameter("pmp_pmp_id", typeof(int));
    
            var related_TypeParameter = related_Type.HasValue ?
                new ObjectParameter("Related_Type", related_Type) :
                new ObjectParameter("Related_Type", typeof(int));
    
            var related_IdParameter = related_Id.HasValue ?
                new ObjectParameter("Related_Id", related_Id) :
                new ObjectParameter("Related_Id", typeof(int));
    
            var follow_Up_Dept_IDParameter = follow_Up_Dept_ID.HasValue ?
                new ObjectParameter("Follow_Up_Dept_ID", follow_Up_Dept_ID) :
                new ObjectParameter("Follow_Up_Dept_ID", typeof(int));
    
            var dept_Dept_idParameter = dept_Dept_id.HasValue ?
                new ObjectParameter("Dept_Dept_id", dept_Dept_id) :
                new ObjectParameter("Dept_Dept_id", typeof(int));
    
            var follow_Up_Emp_IDParameter = follow_Up_Emp_ID.HasValue ?
                new ObjectParameter("Follow_Up_Emp_ID", follow_Up_Emp_ID) :
                new ObjectParameter("Follow_Up_Emp_ID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("Subject", subject) :
                new ObjectParameter("Subject", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var enter_DateParameter = enter_Date != null ?
                new ObjectParameter("Enter_Date", enter_Date) :
                new ObjectParameter("Enter_Date", typeof(string));
    
            var org_NameParameter = org_Name != null ?
                new ObjectParameter("Org_Name", org_Name) :
                new ObjectParameter("Org_Name", typeof(string));
    
            var org_Out_Box_CodeParameter = org_Out_Box_Code != null ?
                new ObjectParameter("Org_Out_Box_Code", org_Out_Box_Code) :
                new ObjectParameter("Org_Out_Box_Code", typeof(string));
    
            var org_Out_Box_DTParameter = org_Out_Box_DT != null ?
                new ObjectParameter("Org_Out_Box_DT", org_Out_Box_DT) :
                new ObjectParameter("Org_Out_Box_DT", typeof(string));
    
            var paper_NoParameter = paper_No != null ?
                new ObjectParameter("Paper_No", paper_No) :
                new ObjectParameter("Paper_No", typeof(string));
    
            var paper_AttachedParameter = paper_Attached != null ?
                new ObjectParameter("Paper_Attached", paper_Attached) :
                new ObjectParameter("Paper_Attached", typeof(string));
    
            var dept_DescParameter = dept_Desc != null ?
                new ObjectParameter("Dept_Desc", dept_Desc) :
                new ObjectParameter("Dept_Desc", typeof(string));
    
            var org_Out_Box_PersonParameter = org_Out_Box_Person != null ?
                new ObjectParameter("Org_Out_Box_Person", org_Out_Box_Person) :
                new ObjectParameter("Org_Out_Box_Person", typeof(string));
    
            var source_TypeParameter = source_Type.HasValue ?
                new ObjectParameter("Source_Type", source_Type) :
                new ObjectParameter("Source_Type", typeof(int));
    
            var org_Dept_NameParameter = org_Dept_Name != null ?
                new ObjectParameter("Org_Dept_Name", org_Dept_Name) :
                new ObjectParameter("Org_Dept_Name", typeof(string));
    
            var sub_Cat_idParameter = sub_Cat_id.HasValue ?
                new ObjectParameter("sub_Cat_id", sub_Cat_id) :
                new ObjectParameter("sub_Cat_id", typeof(int));
    
            var finishedParameter = finished.HasValue ?
                new ObjectParameter("finished", finished) :
                new ObjectParameter("finished", typeof(int));
    
            var foundation_idParameter = foundation_id.HasValue ?
                new ObjectParameter("foundation_id", foundation_id) :
                new ObjectParameter("foundation_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_Save", iD, proj_idParameter, typeParameter, dept_IDParameter, emp_IDParameter, org_IdParameter, group_idParameter, pmp_pmp_idParameter, related_TypeParameter, related_IdParameter, follow_Up_Dept_IDParameter, dept_Dept_idParameter, follow_Up_Emp_IDParameter, statusParameter, subjectParameter, notesParameter, nameParameter, codeParameter, dateParameter, enter_DateParameter, org_NameParameter, org_Out_Box_CodeParameter, org_Out_Box_DTParameter, paper_NoParameter, paper_AttachedParameter, dept_DescParameter, org_Out_Box_PersonParameter, source_TypeParameter, org_Dept_NameParameter, sub_Cat_idParameter, finishedParameter, foundation_idParameter);
        }
    
        public virtual ObjectResult<Outbox_search_par_Result> Outbox_search_par(Nullable<int> selected_group_id, Nullable<int> session_User_group_id, Nullable<int> pmp, Nullable<int> main_cat, Nullable<int> sub_cat, string code, string subject, Nullable<int> org_id, string outbox_date_from, string outbox_date_to, string visa_desc, string notes_word, Nullable<int> related_type_par, Nullable<int> visa_emp, Nullable<int> found_id, Nullable<int> dept_Dept_ID)
        {
            var selected_group_idParameter = selected_group_id.HasValue ?
                new ObjectParameter("selected_group_id", selected_group_id) :
                new ObjectParameter("selected_group_id", typeof(int));
    
            var session_User_group_idParameter = session_User_group_id.HasValue ?
                new ObjectParameter("session_User_group_id", session_User_group_id) :
                new ObjectParameter("session_User_group_id", typeof(int));
    
            var pmpParameter = pmp.HasValue ?
                new ObjectParameter("pmp", pmp) :
                new ObjectParameter("pmp", typeof(int));
    
            var main_catParameter = main_cat.HasValue ?
                new ObjectParameter("main_cat", main_cat) :
                new ObjectParameter("main_cat", typeof(int));
    
            var sub_catParameter = sub_cat.HasValue ?
                new ObjectParameter("sub_cat", sub_cat) :
                new ObjectParameter("sub_cat", typeof(int));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var org_idParameter = org_id.HasValue ?
                new ObjectParameter("Org_id", org_id) :
                new ObjectParameter("Org_id", typeof(int));
    
            var outbox_date_fromParameter = outbox_date_from != null ?
                new ObjectParameter("outbox_date_from", outbox_date_from) :
                new ObjectParameter("outbox_date_from", typeof(string));
    
            var outbox_date_toParameter = outbox_date_to != null ?
                new ObjectParameter("outbox_date_to", outbox_date_to) :
                new ObjectParameter("outbox_date_to", typeof(string));
    
            var visa_descParameter = visa_desc != null ?
                new ObjectParameter("visa_desc", visa_desc) :
                new ObjectParameter("visa_desc", typeof(string));
    
            var notes_wordParameter = notes_word != null ?
                new ObjectParameter("notes_word", notes_word) :
                new ObjectParameter("notes_word", typeof(string));
    
            var related_type_parParameter = related_type_par.HasValue ?
                new ObjectParameter("Related_type_par", related_type_par) :
                new ObjectParameter("Related_type_par", typeof(int));
    
            var visa_empParameter = visa_emp.HasValue ?
                new ObjectParameter("visa_emp", visa_emp) :
                new ObjectParameter("visa_emp", typeof(int));
    
            var found_idParameter = found_id.HasValue ?
                new ObjectParameter("found_id", found_id) :
                new ObjectParameter("found_id", typeof(int));
    
            var dept_Dept_IDParameter = dept_Dept_ID.HasValue ?
                new ObjectParameter("Dept_Dept_ID", dept_Dept_ID) :
                new ObjectParameter("Dept_Dept_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_search_par_Result>("Outbox_search_par", selected_group_idParameter, session_User_group_idParameter, pmpParameter, main_catParameter, sub_catParameter, codeParameter, subjectParameter, org_idParameter, outbox_date_fromParameter, outbox_date_toParameter, visa_descParameter, notes_wordParameter, related_type_parParameter, visa_empParameter, found_idParameter, dept_Dept_IDParameter);
        }
    
        public virtual ObjectResult<Outbox_Select_Result> Outbox_Select(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_Select_Result>("Outbox_Select", iDParameter);
        }
    
        public virtual ObjectResult<Outbox_SelectByOrg_Result> Outbox_SelectByOrg(Nullable<int> org_ID)
        {
            var org_IDParameter = org_ID.HasValue ?
                new ObjectParameter("Org_ID", org_ID) :
                new ObjectParameter("Org_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_SelectByOrg_Result>("Outbox_SelectByOrg", org_IDParameter);
        }
    
        public virtual int Outbox_Track_Manager_Delete(Nullable<int> outbox_id)
        {
            var outbox_idParameter = outbox_id.HasValue ?
                new ObjectParameter("Outbox_id", outbox_id) :
                new ObjectParameter("Outbox_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_Track_Manager_Delete", outbox_idParameter);
        }
    
        public virtual int Outbox_Track_Manager_Save(ObjectParameter outbox_id, Nullable<int> status, Nullable<int> iS_New_Mail, Nullable<int> have_Follow, Nullable<int> have_Visa, Nullable<int> iS_Old_Mail, Nullable<int> pmp_id, Nullable<int> all_visa_sent, Nullable<int> parent_pmp_id, Nullable<int> type_Track, string visa_Desc)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var iS_New_MailParameter = iS_New_Mail.HasValue ?
                new ObjectParameter("IS_New_Mail", iS_New_Mail) :
                new ObjectParameter("IS_New_Mail", typeof(int));
    
            var have_FollowParameter = have_Follow.HasValue ?
                new ObjectParameter("Have_Follow", have_Follow) :
                new ObjectParameter("Have_Follow", typeof(int));
    
            var have_VisaParameter = have_Visa.HasValue ?
                new ObjectParameter("Have_Visa", have_Visa) :
                new ObjectParameter("Have_Visa", typeof(int));
    
            var iS_Old_MailParameter = iS_Old_Mail.HasValue ?
                new ObjectParameter("IS_Old_Mail", iS_Old_Mail) :
                new ObjectParameter("IS_Old_Mail", typeof(int));
    
            var pmp_idParameter = pmp_id.HasValue ?
                new ObjectParameter("pmp_id", pmp_id) :
                new ObjectParameter("pmp_id", typeof(int));
    
            var all_visa_sentParameter = all_visa_sent.HasValue ?
                new ObjectParameter("All_visa_sent", all_visa_sent) :
                new ObjectParameter("All_visa_sent", typeof(int));
    
            var parent_pmp_idParameter = parent_pmp_id.HasValue ?
                new ObjectParameter("parent_pmp_id", parent_pmp_id) :
                new ObjectParameter("parent_pmp_id", typeof(int));
    
            var type_TrackParameter = type_Track.HasValue ?
                new ObjectParameter("Type_Track", type_Track) :
                new ObjectParameter("Type_Track", typeof(int));
    
            var visa_DescParameter = visa_Desc != null ?
                new ObjectParameter("Visa_Desc", visa_Desc) :
                new ObjectParameter("Visa_Desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_Track_Manager_Save", outbox_id, statusParameter, iS_New_MailParameter, have_FollowParameter, have_VisaParameter, iS_Old_MailParameter, pmp_idParameter, all_visa_sentParameter, parent_pmp_idParameter, type_TrackParameter, visa_DescParameter);
        }
    
        public virtual ObjectResult<Outbox_Track_Manager_Select_Result> Outbox_Track_Manager_Select(Nullable<int> outbox_id)
        {
            var outbox_idParameter = outbox_id.HasValue ?
                new ObjectParameter("Outbox_id", outbox_id) :
                new ObjectParameter("Outbox_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_Track_Manager_Select_Result>("Outbox_Track_Manager_Select", outbox_idParameter);
        }
    
        public virtual int Outbox_Visa_Delete(Nullable<int> visa_Id)
        {
            var visa_IdParameter = visa_Id.HasValue ?
                new ObjectParameter("Visa_Id", visa_Id) :
                new ObjectParameter("Visa_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_Visa_Delete", visa_IdParameter);
        }
    
        public virtual int Outbox_visa_emp_save(Nullable<int> visa_Id, Nullable<int> emp_ID, Nullable<int> sender_ID)
        {
            var visa_IdParameter = visa_Id.HasValue ?
                new ObjectParameter("Visa_Id", visa_Id) :
                new ObjectParameter("Visa_Id", typeof(int));
    
            var emp_IDParameter = emp_ID.HasValue ?
                new ObjectParameter("Emp_ID", emp_ID) :
                new ObjectParameter("Emp_ID", typeof(int));
    
            var sender_IDParameter = sender_ID.HasValue ?
                new ObjectParameter("Sender_ID", sender_ID) :
                new ObjectParameter("Sender_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_visa_emp_save", visa_IdParameter, emp_IDParameter, sender_IDParameter);
        }
    
        public virtual int Outbox_Visa_Follows_Delete(Nullable<int> follow_ID)
        {
            var follow_IDParameter = follow_ID.HasValue ?
                new ObjectParameter("Follow_ID", follow_ID) :
                new ObjectParameter("Follow_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_Visa_Follows_Delete", follow_IDParameter);
        }
    
        public virtual int Outbox_Visa_Follows_Save(ObjectParameter follow_ID, Nullable<int> outbox_ID, Nullable<int> visa_Emp_id, Nullable<int> type_Follow, string descrption, string date, string time_follow, Nullable<int> entery_pmp_id)
        {
            var outbox_IDParameter = outbox_ID.HasValue ?
                new ObjectParameter("Outbox_ID", outbox_ID) :
                new ObjectParameter("Outbox_ID", typeof(int));
    
            var visa_Emp_idParameter = visa_Emp_id.HasValue ?
                new ObjectParameter("Visa_Emp_id", visa_Emp_id) :
                new ObjectParameter("Visa_Emp_id", typeof(int));
    
            var type_FollowParameter = type_Follow.HasValue ?
                new ObjectParameter("Type_Follow", type_Follow) :
                new ObjectParameter("Type_Follow", typeof(int));
    
            var descrptionParameter = descrption != null ?
                new ObjectParameter("Descrption", descrption) :
                new ObjectParameter("Descrption", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var time_followParameter = time_follow != null ?
                new ObjectParameter("time_follow", time_follow) :
                new ObjectParameter("time_follow", typeof(string));
    
            var entery_pmp_idParameter = entery_pmp_id.HasValue ?
                new ObjectParameter("entery_pmp_id", entery_pmp_id) :
                new ObjectParameter("entery_pmp_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_Visa_Follows_Save", follow_ID, outbox_IDParameter, visa_Emp_idParameter, type_FollowParameter, descrptionParameter, dateParameter, time_followParameter, entery_pmp_idParameter);
        }
    
        public virtual ObjectResult<Outbox_Visa_Follows_Search_Result> Outbox_Visa_Follows_Search(Nullable<int> outbox_ID, Nullable<int> visa_Emp_id, Nullable<int> entery_pmp_id, Nullable<int> type_Follow, byte[] file_data, string descrption, string date, string time_follow, string file_name, string file_ext)
        {
            var outbox_IDParameter = outbox_ID.HasValue ?
                new ObjectParameter("Outbox_ID", outbox_ID) :
                new ObjectParameter("Outbox_ID", typeof(int));
    
            var visa_Emp_idParameter = visa_Emp_id.HasValue ?
                new ObjectParameter("Visa_Emp_id", visa_Emp_id) :
                new ObjectParameter("Visa_Emp_id", typeof(int));
    
            var entery_pmp_idParameter = entery_pmp_id.HasValue ?
                new ObjectParameter("entery_pmp_id", entery_pmp_id) :
                new ObjectParameter("entery_pmp_id", typeof(int));
    
            var type_FollowParameter = type_Follow.HasValue ?
                new ObjectParameter("Type_Follow", type_Follow) :
                new ObjectParameter("Type_Follow", typeof(int));
    
            var file_dataParameter = file_data != null ?
                new ObjectParameter("File_data", file_data) :
                new ObjectParameter("File_data", typeof(byte[]));
    
            var descrptionParameter = descrption != null ?
                new ObjectParameter("Descrption", descrption) :
                new ObjectParameter("Descrption", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var time_followParameter = time_follow != null ?
                new ObjectParameter("time_follow", time_follow) :
                new ObjectParameter("time_follow", typeof(string));
    
            var file_nameParameter = file_name != null ?
                new ObjectParameter("File_name", file_name) :
                new ObjectParameter("File_name", typeof(string));
    
            var file_extParameter = file_ext != null ?
                new ObjectParameter("File_ext", file_ext) :
                new ObjectParameter("File_ext", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_Visa_Follows_Search_Result>("Outbox_Visa_Follows_Search", outbox_IDParameter, visa_Emp_idParameter, entery_pmp_idParameter, type_FollowParameter, file_dataParameter, descrptionParameter, dateParameter, time_followParameter, file_nameParameter, file_extParameter);
        }
    
        public virtual ObjectResult<Outbox_Visa_Follows_Select_Result> Outbox_Visa_Follows_Select(Nullable<int> follow_ID)
        {
            var follow_IDParameter = follow_ID.HasValue ?
                new ObjectParameter("Follow_ID", follow_ID) :
                new ObjectParameter("Follow_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_Visa_Follows_Select_Result>("Outbox_Visa_Follows_Select", follow_IDParameter);
        }
    
        public virtual ObjectResult<Outbox_Visa_Follows_Select_For_Doc_Result> Outbox_Visa_Follows_Select_For_Doc(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_Visa_Follows_Select_For_Doc_Result>("Outbox_Visa_Follows_Select_For_Doc", idParameter);
        }
    
        public virtual int Outbox_Visa_Save(ObjectParameter visa_Id, Nullable<int> outbox_ID, Nullable<int> important_Degree, Nullable<int> dept_ID, Nullable<int> emp_ID, Nullable<int> visa_Satus, string visa_Desc, string visa_date, string important_Degree_Txt, string dept_ID_Txt, string emp_ID_Txt, string visa_Period, Nullable<int> follow_Up_Dept_ID, Nullable<int> follow_Up_Emp_ID, string follow_Up_Notes, string saving_file, string dead_Line_DT, Nullable<int> visa_Goal_ID, Nullable<int> mail_sent)
        {
            var outbox_IDParameter = outbox_ID.HasValue ?
                new ObjectParameter("Outbox_ID", outbox_ID) :
                new ObjectParameter("Outbox_ID", typeof(int));
    
            var important_DegreeParameter = important_Degree.HasValue ?
                new ObjectParameter("Important_Degree", important_Degree) :
                new ObjectParameter("Important_Degree", typeof(int));
    
            var dept_IDParameter = dept_ID.HasValue ?
                new ObjectParameter("Dept_ID", dept_ID) :
                new ObjectParameter("Dept_ID", typeof(int));
    
            var emp_IDParameter = emp_ID.HasValue ?
                new ObjectParameter("Emp_ID", emp_ID) :
                new ObjectParameter("Emp_ID", typeof(int));
    
            var visa_SatusParameter = visa_Satus.HasValue ?
                new ObjectParameter("Visa_Satus", visa_Satus) :
                new ObjectParameter("Visa_Satus", typeof(int));
    
            var visa_DescParameter = visa_Desc != null ?
                new ObjectParameter("Visa_Desc", visa_Desc) :
                new ObjectParameter("Visa_Desc", typeof(string));
    
            var visa_dateParameter = visa_date != null ?
                new ObjectParameter("Visa_date", visa_date) :
                new ObjectParameter("Visa_date", typeof(string));
    
            var important_Degree_TxtParameter = important_Degree_Txt != null ?
                new ObjectParameter("Important_Degree_Txt", important_Degree_Txt) :
                new ObjectParameter("Important_Degree_Txt", typeof(string));
    
            var dept_ID_TxtParameter = dept_ID_Txt != null ?
                new ObjectParameter("Dept_ID_Txt", dept_ID_Txt) :
                new ObjectParameter("Dept_ID_Txt", typeof(string));
    
            var emp_ID_TxtParameter = emp_ID_Txt != null ?
                new ObjectParameter("Emp_ID_Txt", emp_ID_Txt) :
                new ObjectParameter("Emp_ID_Txt", typeof(string));
    
            var visa_PeriodParameter = visa_Period != null ?
                new ObjectParameter("Visa_Period", visa_Period) :
                new ObjectParameter("Visa_Period", typeof(string));
    
            var follow_Up_Dept_IDParameter = follow_Up_Dept_ID.HasValue ?
                new ObjectParameter("Follow_Up_Dept_ID", follow_Up_Dept_ID) :
                new ObjectParameter("Follow_Up_Dept_ID", typeof(int));
    
            var follow_Up_Emp_IDParameter = follow_Up_Emp_ID.HasValue ?
                new ObjectParameter("Follow_Up_Emp_ID", follow_Up_Emp_ID) :
                new ObjectParameter("Follow_Up_Emp_ID", typeof(int));
    
            var follow_Up_NotesParameter = follow_Up_Notes != null ?
                new ObjectParameter("Follow_Up_Notes", follow_Up_Notes) :
                new ObjectParameter("Follow_Up_Notes", typeof(string));
    
            var saving_fileParameter = saving_file != null ?
                new ObjectParameter("saving_file", saving_file) :
                new ObjectParameter("saving_file", typeof(string));
    
            var dead_Line_DTParameter = dead_Line_DT != null ?
                new ObjectParameter("Dead_Line_DT", dead_Line_DT) :
                new ObjectParameter("Dead_Line_DT", typeof(string));
    
            var visa_Goal_IDParameter = visa_Goal_ID.HasValue ?
                new ObjectParameter("Visa_Goal_ID", visa_Goal_ID) :
                new ObjectParameter("Visa_Goal_ID", typeof(int));
    
            var mail_sentParameter = mail_sent.HasValue ?
                new ObjectParameter("mail_sent", mail_sent) :
                new ObjectParameter("mail_sent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Outbox_Visa_Save", visa_Id, outbox_IDParameter, important_DegreeParameter, dept_IDParameter, emp_IDParameter, visa_SatusParameter, visa_DescParameter, visa_dateParameter, important_Degree_TxtParameter, dept_ID_TxtParameter, emp_ID_TxtParameter, visa_PeriodParameter, follow_Up_Dept_IDParameter, follow_Up_Emp_IDParameter, follow_Up_NotesParameter, saving_fileParameter, dead_Line_DTParameter, visa_Goal_IDParameter, mail_sentParameter);
        }
    
        public virtual ObjectResult<Outbox_Visa_Select_Result> Outbox_Visa_Select(Nullable<int> visa_Id)
        {
            var visa_IdParameter = visa_Id.HasValue ?
                new ObjectParameter("Visa_Id", visa_Id) :
                new ObjectParameter("Visa_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Outbox_Visa_Select_Result>("Outbox_Visa_Select", visa_IdParameter);
        }
    
        public virtual ObjectResult<outbox_Visa_Select_For_Doc_Result> outbox_Visa_Select_For_Doc(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<outbox_Visa_Select_For_Doc_Result>("outbox_Visa_Select_For_Doc", idParameter);
        }
    
        public virtual ObjectResult<OutboxInbox_SelectByOrg_Result> OutboxInbox_SelectByOrg(Nullable<int> org_ID)
        {
            var org_IDParameter = org_ID.HasValue ?
                new ObjectParameter("Org_ID", org_ID) :
                new ObjectParameter("Org_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutboxInbox_SelectByOrg_Result>("OutboxInbox_SelectByOrg", org_IDParameter);
        }
    
        public virtual ObjectResult<outboxinside_data_Result> outboxinside_data(Nullable<int> outbox_id)
        {
            var outbox_idParameter = outbox_id.HasValue ?
                new ObjectParameter("outbox_id", outbox_id) :
                new ObjectParameter("outbox_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<outboxinside_data_Result>("outboxinside_data", outbox_idParameter);
        }
    
        public virtual ObjectResult<OutboxVisaEmpSelect_Result> OutboxVisaEmpSelect(Nullable<int> visa_Id)
        {
            var visa_IdParameter = visa_Id.HasValue ?
                new ObjectParameter("Visa_Id", visa_Id) :
                new ObjectParameter("Visa_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutboxVisaEmpSelect_Result>("OutboxVisaEmpSelect", visa_IdParameter);
        }
    
        public virtual ObjectResult<OutboxVisaEmpSelectOutboxId_Result> OutboxVisaEmpSelectOutboxId(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutboxVisaEmpSelectOutboxId_Result>("OutboxVisaEmpSelectOutboxId", iDParameter);
        }
    
        public virtual ObjectResult<OutboxVisaEmpSelectOutboxId1_Result> OutboxVisaEmpSelectOutboxId1(Nullable<int> outbox_Id)
        {
            var outbox_IdParameter = outbox_Id.HasValue ?
                new ObjectParameter("Outbox_Id", outbox_Id) :
                new ObjectParameter("Outbox_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutboxVisaEmpSelectOutboxId1_Result>("OutboxVisaEmpSelectOutboxId1", outbox_IdParameter);
        }
    
        public virtual ObjectResult<OutboxVisaEmpSelectVisa_Id_Result> OutboxVisaEmpSelectVisa_Id(Nullable<int> visa_Id)
        {
            var visa_IdParameter = visa_Id.HasValue ?
                new ObjectParameter("Visa_Id", visa_Id) :
                new ObjectParameter("Visa_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutboxVisaEmpSelectVisa_Id_Result>("OutboxVisaEmpSelectVisa_Id", visa_IdParameter);
        }
    
        public virtual int SPOutbox_Visa_EmpDelete(Nullable<int> visa_Id)
        {
            var visa_IdParameter = visa_Id.HasValue ?
                new ObjectParameter("Visa_Id", visa_Id) :
                new ObjectParameter("Visa_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPOutbox_Visa_EmpDelete", visa_IdParameter);
        }
    
        public virtual int SPOutboxCatDelete(Nullable<int> outbox_id)
        {
            var outbox_idParameter = outbox_id.HasValue ?
                new ObjectParameter("outbox_id", outbox_id) :
                new ObjectParameter("outbox_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPOutboxCatDelete", outbox_idParameter);
        }
    
        public virtual ObjectResult<SP_vw_outbox_DateSubject_Result> SP_vw_outbox_DateSubject(Nullable<int> groupID, Nullable<int> projectID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("groupID", groupID) :
                new ObjectParameter("groupID", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_vw_outbox_DateSubject_Result>("SP_vw_outbox_DateSubject", groupIDParameter, projectIDParameter);
        }
    
        public virtual ObjectResult<string> get_OutboxVisaEmps(Nullable<int> visa_ID)
        {
            var visa_IDParameter = visa_ID.HasValue ?
                new ObjectParameter("visa_ID", visa_ID) :
                new ObjectParameter("visa_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("get_OutboxVisaEmps", visa_IDParameter);
        }
    
        public virtual int update_outbox_relatedtype(Nullable<int> iD, Nullable<int> related_Type, Nullable<int> related_Id)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var related_TypeParameter = related_Type.HasValue ?
                new ObjectParameter("Related_Type", related_Type) :
                new ObjectParameter("Related_Type", typeof(int));
    
            var related_IdParameter = related_Id.HasValue ?
                new ObjectParameter("Related_Id", related_Id) :
                new ObjectParameter("Related_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_outbox_relatedtype", iDParameter, related_TypeParameter, related_IdParameter);
        }
    }
}
