//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OutboxContext : DbContext
    {
        public OutboxContext()
            : base("name=OutboxContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Outbox> Outboxes { get; set; }
        public virtual DbSet<Outbox_Main_Categories> Outbox_Main_Categories { get; set; }
        public virtual DbSet<Outbox_Sub_Categories> Outbox_Sub_Categories { get; set; }
        public virtual DbSet<Outbox_Track_Emp> Outbox_Track_Emp { get; set; }
        public virtual DbSet<Outbox_Track_Manager> Outbox_Track_Manager { get; set; }
        public virtual DbSet<Outbox_Visa> Outbox_Visa { get; set; }
        public virtual DbSet<Outbox_Visa_Emp> Outbox_Visa_Emp { get; set; }
        public virtual DbSet<Outbox_Visa_Follows> Outbox_Visa_Follows { get; set; }
        public virtual DbSet<Outbox_follow_emp> Outbox_follow_emp { get; set; }
    }
}
