//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public long Proj_id { get; set; }
        public string Proj_Title { get; set; }
        public string Proj_Brief { get; set; }
        public Nullable<decimal> Proj_InitValue { get; set; }
        public Nullable<long> Dept_Dept_id { get; set; }
        public Nullable<long> pmp_pmp_id { get; set; }
        public Nullable<int> Proj_is_commit { get; set; }
        public byte[] Proj_End_Document { get; set; }
        public string Proj_Code { get; set; }
        public string Proj_Creation_Date { get; set; }
        public string proj_start_date { get; set; }
        public string Proj_End_Date { get; set; }
        public Nullable<int> Proj_is_refused { get; set; }
        public Nullable<int> Proj_is_repeated { get; set; }
        public string Proj_Notes { get; set; }
        public Nullable<long> prio_prio_id { get; set; }
        public string Proj_End_Note { get; set; }
        public string Proj_End_Document_Name { get; set; }
        public string Proj_End_Document_Type { get; set; }
        public Nullable<int> Protocol_ID { get; set; }
        public Nullable<int> proj_sug_type { get; set; }
        public string opportunities { get; set; }
        public string dangers { get; set; }
        public string strengths { get; set; }
        public string weaknesses { get; set; }
        public Nullable<int> Class_id { get; set; }
        public Nullable<int> internal_external { get; set; }
        public Nullable<int> connected_to_proj { get; set; }
        public string methodology { get; set; }
        public string proj_gov_desc { get; set; }
        public Nullable<decimal> Balance_Suggest_Initial { get; set; }
        public Nullable<decimal> Balance_Suggest_Finial { get; set; }
        public Nullable<decimal> Balance_Suggest_Approved { get; set; }
        public string project_cause { get; set; }
        public string project_innovation { get; set; }
    }
}
namespace EFModels
{
    using System;
    
    public partial class get_all_projects_Result
    {
        public long Proj_id { get; set; }
        public string Proj_Title { get; set; }
    }
}
