//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Employee_Managers_DT
// Date Generated:	19-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Employee_Managers_DT
    {
        public enum Enum_Employee_Managers_DT
        {
            Emp_Mngr_ID, Emp_ID, Mngr_Emp_ID, Mngr_Level, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Emp_Mngr_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Mngr_Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Mngr_Level;
		
    }

