//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmghaith using Mcit Generator
// Class Name:		Employee_publicdata_DT
// Date Generated:	26-03-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Employee_publicdata_DT
    {
        public enum Enum_Employee_publicdata_DT
        {
            id, pmp_id, noofemployee, englishlevel, is_manager, mobile, phone, mail, current_tasks, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 noofemployee;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 englishlevel;
		
		/// <summary>
		/// 
		/// </summary>
		public Boolean is_manager;
		
		/// <summary>
		/// 
		/// </summary>
		public String mobile;
		
		/// <summary>
		/// 
		/// </summary>
		public String phone;
		
		/// <summary>
		/// 
		/// </summary>
		public String mail;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_tasks;
		
    }

