//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\mmabdelmalek using Mcit Generator
// Class Name:		Employee_Experience_DT
// Date Generated:	10-12-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Employee_Experience_DT
    {
        public enum Enum_Employee_Experience_DT
        {
            id, pmp_id, organization, job_title, desc, FromDate, ToDate, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String organization;
		
		/// <summary>
		/// 
		/// </summary>
		public String job_title;
		
		/// <summary>
		/// 
		/// </summary>
		public String desc;
		
		/// <summary>
		/// 
		/// </summary>
		public String FromDate;
		
		/// <summary>
		/// 
		/// </summary>
		public String ToDate;
		
    }

