//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmghaith using Mcit Generator
// Class Name:		Employee_Ex_Training_DT
// Date Generated:	01-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Employee_Ex_Training_DT
    {
        public enum Enum_Employee_Ex_Training_DT
        {
            id, pmp_id, course_name, start_date, end_date, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String course_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String start_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String end_date;
		
    }

