using System;
using System.Collections.Generic;
using System.Text;

//Generated by frogman (aka H) Enterprise Library Data Layer Generator  v 1.0
//©2008 frogmansoft 


namespace CAR_STORE.Managers.Core
{
	public class ManagerBase
	{ }
}
