//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Projects_ManagementEntities10 : DbContext
{
    public Projects_ManagementEntities10()
        : base("name=Projects_ManagementEntities10")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Commission> Commission { get; set; }
    public virtual DbSet<Commission_Files> Commission_Files { get; set; }
    public virtual DbSet<Commission_Track_Emp> Commission_Track_Emp { get; set; }
    public virtual DbSet<Commission_Visa> Commission_Visa { get; set; }
    public virtual DbSet<Commission_Visa_Emp> Commission_Visa_Emp { get; set; }
    public virtual DbSet<Commission_Visa_Follows> Commission_Visa_Follows { get; set; }
    public virtual DbSet<Commission_follow_emp> Commission_follow_emp { get; set; }

    public virtual ObjectResult<com_get_emp_visa> get_Emp_Visa_Follow(Nullable<int> commission_ID)
    {
        var commission_IDParameter = commission_ID.HasValue ?
            new ObjectParameter("Commission_ID", commission_ID) :
            new ObjectParameter("Commission_ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<com_get_emp_visa>("get_Emp_Visa_Follow", commission_IDParameter);
    }

    public virtual ObjectResult<get_Visa_Follow> get_Visa_Follow(Nullable<int> commission_ID)
    {
        var commission_IDParameter = commission_ID.HasValue ?
            new ObjectParameter("Commission_ID", commission_ID) :
            new ObjectParameter("Commission_ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Visa_Follow>("get_Visa_Follow", commission_IDParameter);
    }

    public virtual ObjectResult<get_comm_infor_formail> get_comm_infor_formail(Nullable<int> commission_ID)
    {
        var commission_IDParameter = commission_ID.HasValue ?
            new ObjectParameter("Commission_ID", commission_ID) :
            new ObjectParameter("Commission_ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_comm_infor_formail>("get_comm_infor_formail", commission_IDParameter);
    }

    public virtual ObjectResult<Fil_Visa_foremployee> Fil_Visa_foremployee(Nullable<int> visa_Id)
    {
        var visa_IdParameter = visa_Id.HasValue ?
            new ObjectParameter("Visa_Id", visa_Id) :
            new ObjectParameter("Visa_Id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fil_Visa_foremployee>("Fil_Visa_foremployee", visa_IdParameter);
    }

    public virtual ObjectResult<Get_Visa_foremployee> Get_Visa_foremployee(Nullable<int> visa_Id)
    {
        var visa_IdParameter = visa_Id.HasValue ?
            new ObjectParameter("Visa_Id", visa_Id) :
            new ObjectParameter("Visa_Id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Visa_foremployee>("Get_Visa_foremployee", visa_IdParameter);
    }

    public virtual ObjectResult<get_commission_visa_emp> get_commission_visa_emp(Nullable<int> visa_Id)
    {
        var visa_IdParameter = visa_Id.HasValue ?
            new ObjectParameter("Visa_Id", visa_Id) :
            new ObjectParameter("Visa_Id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_commission_visa_emp>("get_commission_visa_emp", visa_IdParameter);
    }

    public virtual ObjectResult<commission_search_par_new> commission_search_par_new(Nullable<int> group_id, Nullable<int> pmp, string subject, string com_date_from, string com_date_to, string visa_desc, string notes_word, Nullable<int> visa_emp, Nullable<int> found_id)
    {
        var group_idParameter = group_id.HasValue ?
            new ObjectParameter("group_id", group_id) :
            new ObjectParameter("group_id", typeof(int));

        var pmpParameter = pmp.HasValue ?
            new ObjectParameter("pmp", pmp) :
            new ObjectParameter("pmp", typeof(int));

        var subjectParameter = subject != null ?
            new ObjectParameter("subject", subject) :
            new ObjectParameter("subject", typeof(string));

        var com_date_fromParameter = com_date_from != null ?
            new ObjectParameter("com_date_from", com_date_from) :
            new ObjectParameter("com_date_from", typeof(string));

        var com_date_toParameter = com_date_to != null ?
            new ObjectParameter("com_date_to", com_date_to) :
            new ObjectParameter("com_date_to", typeof(string));

        var visa_descParameter = visa_desc != null ?
            new ObjectParameter("visa_desc", visa_desc) :
            new ObjectParameter("visa_desc", typeof(string));

        var notes_wordParameter = notes_word != null ?
            new ObjectParameter("notes_word", notes_word) :
            new ObjectParameter("notes_word", typeof(string));

        var visa_empParameter = visa_emp.HasValue ?
            new ObjectParameter("visa_emp", visa_emp) :
            new ObjectParameter("visa_emp", typeof(int));

        var found_idParameter = found_id.HasValue ?
            new ObjectParameter("found_id", found_id) :
            new ObjectParameter("found_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<commission_search_par_new>("commission_search_par_new", group_idParameter, pmpParameter, subjectParameter, com_date_fromParameter, com_date_toParameter, visa_descParameter, notes_wordParameter, visa_empParameter, found_idParameter);
    }
}
