//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Projects_ManagementEntities10 : DbContext
{
    public Projects_ManagementEntities10()
        : base("name=Projects_ManagementEntities10")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Commission> Commission { get; set; }
    public virtual DbSet<Commission_Files> Commission_Files { get; set; }
    public virtual DbSet<Commission_Track_Emp> Commission_Track_Emp { get; set; }
    public virtual DbSet<Commission_Visa> Commission_Visa { get; set; }
    public virtual DbSet<Commission_Visa_Emp> Commission_Visa_Emp { get; set; }
    public virtual DbSet<Commission_Visa_Follows> Commission_Visa_Follows { get; set; }
    public virtual DbSet<Commission_follow_emp> Commission_follow_emp { get; set; }

    public virtual ObjectResult<com_get_emp_visa> get_Emp_Visa_Follow(Nullable<int> commission_ID)
    {
        var commission_IDParameter = commission_ID.HasValue ?
            new ObjectParameter("Commission_ID", commission_ID) :
            new ObjectParameter("Commission_ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<com_get_emp_visa>("get_Emp_Visa_Follow", commission_IDParameter);
    }
}
