//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Commission
{
    public int ID { get; set; }
    public Nullable<int> Proj_id { get; set; }
    public string Name { get; set; }
    public string Code { get; set; }
    public string Date { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<int> Dept_ID { get; set; }
    public Nullable<int> Emp_ID { get; set; }
    public Nullable<int> Org_Id { get; set; }
    public string Org_Name { get; set; }
    public string Org_Out_Box_Code { get; set; }
    public string Org_Out_Box_DT { get; set; }
    public string Org_Out_Box_Person { get; set; }
    public string Subject { get; set; }
    public Nullable<int> Related_Type { get; set; }
    public Nullable<int> Related_Id { get; set; }
    public string Notes { get; set; }
    public string Paper_No { get; set; }
    public string Paper_Attached { get; set; }
    public Nullable<int> Follow_Up_Dept_ID { get; set; }
    public Nullable<int> Follow_Up_Emp_ID { get; set; }
    public string Dept_Desc { get; set; }
    public Nullable<int> Source_Type { get; set; }
    public Nullable<int> Status { get; set; }
    public string Org_Dept_Name { get; set; }
    public string Enter_Date { get; set; }
    public Nullable<int> Dept_Dept_ID { get; set; }
    public Nullable<int> Group_id { get; set; }
    public Nullable<int> pmp_pmp_id { get; set; }
    public Nullable<int> sub_Cat_id { get; set; }
    public Nullable<int> finished { get; set; }
    public Nullable<int> Resp_emp_close { get; set; }
    public Nullable<int> Actual_emp_close { get; set; }
    public string Date_close { get; set; }
    public Nullable<int> foundation_id { get; set; }
}

public partial class Commission_Files
{
    public int Commission_File_ID { get; set; }
    public Nullable<int> Commission_ID { get; set; }
    public Nullable<int> Inbox_Or_Outbox { get; set; }
    public Nullable<int> Original_Or_Attached { get; set; }
    public byte[] File_data { get; set; }
    public string File_name { get; set; }
    public string File_ext { get; set; }
}

public partial class Commission_follow_emp
{
    public int id { get; set; }
    public Nullable<int> pmp_id { get; set; }
    public Nullable<int> Have_follow { get; set; }
    public Nullable<int> Commission_id { get; set; }
}

public partial class Commission_Track_Emp
{
    public int ID { get; set; }
    public int Commission_id { get; set; }
    public Nullable<int> Emp_ID { get; set; }
    public Nullable<int> Commission_Status { get; set; }
    public Nullable<int> Type_Track_emp { get; set; }
}

public partial class Commission_Visa
{
    public int Visa_Id { get; set; }
    public Nullable<int> Commission_ID { get; set; }
    public string Visa_date { get; set; }
    public Nullable<int> Important_Degree { get; set; }
    public Nullable<int> Dept_ID { get; set; }
    public Nullable<int> Emp_ID { get; set; }
    public string Important_Degree_Txt { get; set; }
    public string Dept_ID_Txt { get; set; }
    public string Emp_ID_Txt { get; set; }
    public string Visa_Desc { get; set; }
    public string Visa_Period { get; set; }
    public Nullable<int> Visa_Satus { get; set; }
    public Nullable<int> Follow_Up_Dept_ID { get; set; }
    public Nullable<int> Follow_Up_Emp_ID { get; set; }
    public string Follow_Up_Notes { get; set; }
    public string saving_file { get; set; }
    public string Dead_Line_DT { get; set; }
    public Nullable<int> Visa_Goal_ID { get; set; }
    public Nullable<int> mail_sent { get; set; }
}

public partial class Commission_Visa_Emp
{
    public int Visa_Emp_ID { get; set; }
    public Nullable<int> Visa_Id { get; set; }
    public Nullable<int> Emp_ID { get; set; }
    public Nullable<int> Sender_ID { get; set; }
}

public partial class Commission_Visa_Follows
{
    public int Follow_ID { get; set; }
    public Nullable<int> Commission_ID { get; set; }
    public string Descrption { get; set; }
    public string Date { get; set; }
    public byte[] File_data { get; set; }
    public string File_name { get; set; }
    public string File_ext { get; set; }
    public Nullable<int> Visa_Emp_id { get; set; }
    public Nullable<int> entery_pmp_id { get; set; }
    public string time_follow { get; set; }
    public Nullable<int> Type_Follow { get; set; }
}

public partial class com_get_emp_visa
{
    public long PMP_ID { get; set; }
    public string pmp_name { get; set; }
    public int Commission_ID { get; set; }
}

public partial class Fil_Visa_foremployee
{
    public int Visa_Id { get; set; }
    public string pmp_name { get; set; }
    public int Emp_ID { get; set; }
}

public partial class get_comm_infor_formail
{
    public int Commission_ID { get; set; }
    public int Follow_ID { get; set; }
    public byte[] File_data { get; set; }
    public string File_name { get; set; }
    public string File_ext { get; set; }
    public string Descrption { get; set; }
    public string Date { get; set; }
    public int Visa_Emp_id { get; set; }
    public string pmp_name { get; set; }
}

public partial class get_commission_visa_emp
{
    public int Visa_Id { get; set; }
    public string pmp_name { get; set; }
}

public partial class get_Visa_Follow
{
    public int Follow_ID { get; set; }
    public string File_name { get; set; }
    public string time_follow { get; set; }
    public int Commission_ID { get; set; }
    public string Descrption { get; set; }
    public string Date { get; set; }
    public int Visa_Emp_id { get; set; }
    public string pmp_name { get; set; }
}

public partial class Get_Visa_foremployee
{
    public int Visa_Id { get; set; }
}
