<<<<<<< HEAD
﻿ErrorGeneratingOutput
=======
﻿

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

>>>>>>> 9e3254ace7da6c82bf5edf99eba644c53109f39b
