//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Projects_ManagementEntities : DbContext
{
    public Projects_ManagementEntities()
        : base("name=Projects_ManagementEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Foundations> Foundations { get; set; }
    public virtual DbSet<Admin_Users> Admin_Users { get; set; }
    public virtual DbSet<Admin_Module> Admin_Module { get; set; }
    public virtual DbSet<Admin_Module_Found> Admin_Module_Found { get; set; }
    public virtual DbSet<super_admin> super_admin { get; set; }

    public virtual ObjectResult<AdminUsers_SelectName_Exsit_Result> AdminUsers_SelectName_Exsit(string user_name)
    {
        var user_nameParameter = user_name != null ?
            new ObjectParameter("User_name", user_name) :
            new ObjectParameter("User_name", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminUsers_SelectName_Exsit_Result>("AdminUsers_SelectName_Exsit", user_nameParameter);
    }

    public virtual ObjectResult<Foundations_Followup_Result> Foundations_Followup(Nullable<int> foundation_id)
    {
        var foundation_idParameter = foundation_id.HasValue ?
            new ObjectParameter("foundation_id", foundation_id) :
            new ObjectParameter("foundation_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Foundations_Followup_Result>("Foundations_Followup", foundation_idParameter);
    }

    public virtual ObjectResult<SuperAdminUsers_SelectName_Result> SuperAdminUsers_SelectName(string user_name)
    {
        var user_nameParameter = user_name != null ?
            new ObjectParameter("User_name", user_name) :
            new ObjectParameter("User_name", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuperAdminUsers_SelectName_Result>("SuperAdminUsers_SelectName", user_nameParameter);
    }
}
