//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Foundations
{
    public int Foundation_ID { get; set; }
    public string Foundation_Name { get; set; }
    public Nullable<int> code_archiving { get; set; }
    public Nullable<int> Port { get; set; }
    public string Host { get; set; }
    public string UserName_mail { get; set; }
    public string Password { get; set; }
    public string FromAddress { get; set; }
    public string connection_string { get; set; }
    public Nullable<bool> islocal { get; set; }
}
