//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class inbox_Main_Categories
{
    public int id { get; set; }
    public string Name { get; set; }
    public Nullable<int> group_id { get; set; }
}

public partial class inbox_sub_categories
{
    public int id { get; set; }
    public string name { get; set; }
    public Nullable<int> main_id { get; set; }
}

public partial class get_all_cat_sub_main
{
}

public partial class get_all_subs
{
}

public partial class get_sub_cat_by_main_cat
{
}

public partial class select_main_cat_by_group
{
}
