//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Projects_ManagementEntities_Inbox : DbContext
{
    public Projects_ManagementEntities_Inbox()
        : base("name=Projects_ManagementEntities_Inbox")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<inbox_Main_Categories> inbox_Main_Categories { get; set; }
    public virtual DbSet<inbox_sub_categories> inbox_sub_categories { get; set; }

    public virtual ObjectResult<select_main_cat_by_group> select_main_cat_by_group(Nullable<int> group_id)
    {
        var group_idParameter = group_id.HasValue ?
            new ObjectParameter("group_id", group_id) :
            new ObjectParameter("group_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_main_cat_by_group>("select_main_cat_by_group", group_idParameter);
    }

    public virtual ObjectResult<get_sub_cat_by_main_cat> get_sub_cat_by_main_cat(Nullable<int> cat_id)
    {
        var cat_idParameter = cat_id.HasValue ?
            new ObjectParameter("cat_id", cat_id) :
            new ObjectParameter("cat_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_sub_cat_by_main_cat>("get_sub_cat_by_main_cat", cat_idParameter);
    }

    public virtual ObjectResult<get_all_cat_sub_main> get_all_cat_sub_main(Nullable<int> inbox_id)
    {
        var inbox_idParameter = inbox_id.HasValue ?
            new ObjectParameter("inbox_id", inbox_id) :
            new ObjectParameter("inbox_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_cat_sub_main>("get_all_cat_sub_main", inbox_idParameter);
    }

    public virtual ObjectResult<get_all_subs> get_all_subs(Nullable<int> inbox_id)
    {
        var inbox_idParameter = inbox_id.HasValue ?
            new ObjectParameter("inbox_id", inbox_id) :
            new ObjectParameter("inbox_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_subs>("get_all_subs", inbox_idParameter);
    }
}
