//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\Matta using Mcit Generator
// Class Name:		Employee_Groups_DT
// Date Generated:	26-09-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Employee_Groups_DT
    {
        public enum Enum_Employee_Groups_DT
        {
            ID, Name, foundation_id
        }

        
		/// <summary>
		/// 
		/// </summary>
        public Int64 ID;
            
         public Int32 foundation_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String Name;
		
    }

