//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\izibrahim using Mcit Generator
// Class Name:		Admin_ModulePage_DT
// Date Generated:	13-05-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Admin_ModulePage_DT
    {
        public enum Enum_Admin_ModulePage_DT
        {
            pk_ID, fk_PageID, fk_ModuleID, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 pk_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 fk_PageID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 fk_ModuleID;
		
    }

