//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\mmabdelmalek using Mcit Generator
// Class Name:		Admin_Module_DT
// Date Generated:	15-10-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Admin_Module_DT
    {
        public enum Enum_Admin_Module_DT
        {
            pk_ID, Active, Name, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 pk_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Boolean Active;
		
		/// <summary>
		/// 
		/// </summary>
		public String Name;
		
    }

