//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\Matta using Mcit Generator
// Class Name:		Commitee_DT
// Date Generated:	26-12-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Commitee_DT
    {
        public enum Enum_Commitee_DT
        {
            ID, Commitee_Title, foundation_id
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 ID;
		
		/// <summary>
		/// 
		/// </summary>
		public String Commitee_Title;
      public   int foundation_id;
		
    }

