//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\Matta using Mcit Generator
// Class Name:		commitee_presidents_DT
// Date Generated:	26-12-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class commitee_presidents_DT
    {
        public enum Enum_commitee_presidents_DT
        {
            id, pmp_id, comt_id, dept_id, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 comt_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 dept_id;
		
    }

