//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Visa_DT
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Review_Visa_DT
    {
        public enum Enum_Review_Visa_DT
        {
            Visa_Id, Review_ID, Important_Degree, Dept_ID, Emp_ID, Visa_Satus, Follow_Up_Dept_ID, Follow_Up_Emp_ID, Visa_Goal_ID, mail_sent, Visa_Desc, Visa_date, Important_Degree_Txt, Dept_ID_Txt, Emp_ID_Txt, Visa_Period, Follow_Up_Notes, saving_file, Dead_Line_DT, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Visa_Id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Review_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Important_Degree;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Dept_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Visa_Satus;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Follow_Up_Dept_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Follow_Up_Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Visa_Goal_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 mail_sent;
		
		/// <summary>
		/// 
		/// </summary>
		public String Visa_Desc;
		
		/// <summary>
		/// 
		/// </summary>
		public String Visa_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String Important_Degree_Txt;
		
		/// <summary>
		/// 
		/// </summary>
		public String Dept_ID_Txt;
		
		/// <summary>
		/// 
		/// </summary>
		public String Emp_ID_Txt;
		
		/// <summary>
		/// 
		/// </summary>
		public String Visa_Period;
		
		/// <summary>
		/// 
		/// </summary>
		public String Follow_Up_Notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String saving_file;
		
		/// <summary>
		/// 
		/// </summary>
		public String Dead_Line_DT;
		
    }

