//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Cat_DT
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Review_Cat_DT
    {
        public enum Enum_Review_Cat_DT
        {
            FK_ReviewID, FK_CatID, CatType, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 FK_ReviewID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 FK_CatID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 CatType;
		
    }

