//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Track_Manager_DT
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Review_Track_Manager_DT
    {
        public enum Enum_Review_Track_Manager_DT
        {
            Review_id, status, IS_New_Mail, Have_Follow, Have_Visa, IS_Old_Mail, pmp_id, parent_pmp_id, Type_Track, All_visa_sent, Visa_Desc, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Review_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 IS_New_Mail;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Have_Follow;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Have_Visa;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 IS_Old_Mail;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 parent_pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Type_Track;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 All_visa_sent;
		
		/// <summary>
		/// 
		/// </summary>
		public String Visa_Desc;
		
    }

