//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_sub_categories_DT
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Review_sub_categories_DT
    {
        public enum Enum_Review_sub_categories_DT
        {
            id, main_id, name, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 main_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String name;
		
    }

