//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Track_Emp_DT
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Review_Track_Emp_DT
    {
        public enum Enum_Review_Track_Emp_DT
        {
            ID, Review_id, Emp_ID, Review_Status, Type_Track_emp, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Review_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Review_Status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Type_Track_emp;
		
    }

