//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_DT
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Review_DT
    {
        public enum Enum_Review_DT
        {
            ID, Dept_Dept_ID, Group_id, pmp_pmp_id, Subject, Notes, Code, Date, Enter_Date, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 ID;
		
		/// <summary>
		/// 
		/// </summary>
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Dept_Dept_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Group_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pmp_pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
	
		
		/// <summary>
		/// 
		/// </summary>
		public String Subject;
		
		/// <summary>
		/// 
		/// </summary>
		public String Notes;
		
		/// <summary>
		/// 
		/// </summary>
	
		
		/// <summary>
		/// 
		/// </summary>
		public String Code;
		
		/// <summary>
		/// 
		/// </summary>
		public String Date;
		
		/// <summary>
		/// 
		/// </summary>
		public String Enter_Date;
		
    }

