//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Visa_Emp_DT
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Review_Visa_Emp_DT
    {
        public enum Enum_Review_Visa_Emp_DT
        {
            Visa_Emp_ID, Visa_Id, Emp_ID, Sender_ID, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Visa_Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Visa_Id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Sender_ID;
		
    }

