//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Files_DT
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Review_Files_DT
    {
        public enum Enum_Review_Files_DT
        {
            Review_File_ID, Review_ID, Original_Or_Attached, File_data, File_name, File_ext, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Review_File_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Review_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Original_Or_Attached;
		
		/// <summary>
		/// 
		/// </summary>
		public Byte[] File_data;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_ext;
		
    }

