//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Files_DT
// Date Generated:	26-03-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Files_DT
    {
        public enum Enum_Files_DT
        {
            Files_id, File_note, File_date, File_Name, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Files_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_note;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_Name;
		
    }

