//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		File_Archive_DT
// Date Generated:	20-09-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class File_Archive_DT
    {
        public enum Enum_File_Archive_DT
        {
            id, file_desc, file_data, file_name, file_ext, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String file_desc;
		
		/// <summary>
		/// 
		/// </summary>
		public Byte[] file_data;
		
		/// <summary>
		/// 
		/// </summary>
		public String file_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String file_ext;
		
    }

