//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Foundations_DT
// Date Generated:	07-11-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Foundations_DT
    {
        public enum Enum_Foundations_DT
        {
            Foundation_ID, Foundation_Name, code_archiving, Port, Host, UserName_mail, Password, FromAddress, islocal, connection_string
        }

        
		/// <summary>
		/// 
		/// </summary>
        public Int32 Foundation_ID, code_archiving, Port ;
		
		/// <summary>
		/// 
		/// </summary>
        public String Foundation_Name, Host, UserName_mail, FromAddress, Password, connection_string;
 public bool islocal;


		
    }

