//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Memo_Upload_DT
// Date Generated:	10-10-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Memo_Upload_DT
    {
        public enum Enum_Memo_Upload_DT
        {
            ID, File_Name, File_Ext, File_Title,sector_id
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 ID;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_Name;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_Ext;

        public String File_Title;
        public int sector_id;
		
    }

