//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\Matta using Mcit Generator
// Class Name:		Site_Upload_DT
// Date Generated:	31-12-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Site_Upload_DT
    {
        public enum Enum_Site_Upload_DT
        {
            logo_image, ID, Site_Name, File_Name, File_Ext, logo_file_name, logo_file_Ext, e_signature, foundation_id 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Byte[] logo_image;
		
		/// <summary>
		/// 
		/// </summary>
        public Int32 ID, foundation_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String Site_Name;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_Name;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_Ext;
		
		/// <summary>
		/// 
		/// </summary>
		public String logo_file_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String logo_file_Ext;
		
		/// <summary>
		/// 
		/// </summary>
		public String e_signature;
		
    }

