//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\mmabdelmalek using Mcit Generator
// Class Name:		Users_Permission_DT
// Date Generated:	15-10-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Users_Permission_DT
    {
        public enum Enum_Users_Permission_DT
        {
            ID, pmp_pmp_id, Page_ID, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pmp_pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Page_ID;
		
    }

