//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\Matta using Mcit Generator
// Class Name:		Departments_DT
// Date Generated:	12-11-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Departments_DT
    {
        public enum Enum_Departments_DT
        {
            Dept_id, Dept_type, Dept_parent_id, Sec_sec_id, Dept_name, foundation_id
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int64 Dept_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int64 Dept_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int64 Dept_parent_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int64 Sec_sec_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String Dept_name;

        public int foundation_id;
		
    }

