//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\malmeligi using Mcit Generator
// Class Name:		Organization_DT
// Date Generated:	17-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Organization_DT
    {
        public enum Enum_Organization_DT
        {
            New_ID, Org_ID, Org_Desc,foundation_id, 
        }

        
		/// <summary>
		/// 
		/// </summary>
        public Int32 New_ID, foundation_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Org_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public String Org_Desc;
		
    }

