//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\wmibrahim using Mcit Generator
// Class Name:		Sectors_DT
// Date Generated:	04-03-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



public class Sectors_DT
{
    public enum Enum_Sectors_DT
    {
        Sec_id, Sec_name, foundation_id
    }


    /// <summary>
    /// 
    /// </summary>
    public Int64 Sec_id;

    /// <summary>
    /// 
    /// </summary>
    public String Sec_name;
    public int foundation_id;

}

