//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Course_Tracks_DB
// Date Generated:	24-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Course_Tracks_DB
    {

        #region "Private methods"

        private static Course_Tracks_DT FillInfoObject(SqlDataReader dr)
        {

           Course_Tracks_DT obj_Course_Tracks_DT = new Course_Tracks_DT();

           
		obj_Course_Tracks_DT.id = Convert.ToInt32(dr[Course_Tracks_DT.Enum_Course_Tracks_DT.id.ToString()]);
		obj_Course_Tracks_DT.course_id = dr[Course_Tracks_DT.Enum_Course_Tracks_DT.course_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Course_Tracks_DT.Enum_Course_Tracks_DT.course_id.ToString()]);
		obj_Course_Tracks_DT.track_name = dr[Course_Tracks_DT.Enum_Course_Tracks_DT.track_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Course_Tracks_DT.Enum_Course_Tracks_DT.track_name.ToString()]);

           return obj_Course_Tracks_DT;
        }

        private static SqlParameter[] GetParameters(Course_Tracks_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[3];
           
			
        

        parms[0] = new SqlParameter(Course_Tracks_DT.Enum_Course_Tracks_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Course_Tracks_DT.Enum_Course_Tracks_DT.course_id.ToString(), obj.course_id);

        parms[2] = new SqlParameter(Course_Tracks_DT.Enum_Course_Tracks_DT.track_name.ToString(), obj.track_name);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(Course_Tracks_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Course_Tracks_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Course_Tracks_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Course_Tracks_Delete", Course_Tracks_ID);
                return Course_Tracks_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll(int id,int course_id)
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Course_Tracks_Select", id ,course_id ).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }


       

 

        public static Course_Tracks_DT SelectByID(int Course_Tracks_ID,int course_id)
        {
            try
            {
              if (Course_Tracks_ID > 0)
                {
                SqlDataReader drTableName;
                Course_Tracks_DT oInfo_Course_Tracks_DT = new Course_Tracks_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Course_Tracks_Select", Course_Tracks_ID,course_id);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Course_Tracks_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Course_Tracks_DT;
               }
                else
                    return new Course_Tracks_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

