//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT-B51303A24F\Administrator using Mcit Generator
// Class Name:		course_files_DB
// Date Generated:	29-01-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


public static class course_files_DB
{

    #region "Private methods"

    private static course_files_DT FillInfoObject(SqlDataReader dr)
    {

        course_files_DT obj_course_files_DT = new course_files_DT();


        obj_course_files_DT.id = Convert.ToInt32(dr[course_files_DT.Enum_course_files_DT.id.ToString()]);
        obj_course_files_DT.course_id = dr[course_files_DT.Enum_course_files_DT.course_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[course_files_DT.Enum_course_files_DT.course_id.ToString()]);
        obj_course_files_DT.file_path = dr[course_files_DT.Enum_course_files_DT.file_path.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[course_files_DT.Enum_course_files_DT.file_path.ToString()]);

        return obj_course_files_DT;
    }

    private static SqlParameter[] GetParameters(course_files_DT obj)
    {
        SqlParameter[] parms = new SqlParameter[3];




        parms[0] = new SqlParameter(course_files_DT.Enum_course_files_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(course_files_DT.Enum_course_files_DT.course_id.ToString(), obj.course_id);

        parms[2] = new SqlParameter(course_files_DT.Enum_course_files_DT.file_path.ToString(), obj.file_path);

        return parms;
    }

    #endregion

    #region "DB methods"

    public static int Save(course_files_DT obj)
    {
        try
        {
            SqlParameter[] parms = GetParameters(obj);

            SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "course_files_Save", parms);
            return Convert.ToInt32(parms[0].Value);
        }
        catch (Exception ex)
        {

            return -1;
        }
    }

    public static int Delete(int course_files_ID)
    {
        try
        {
            SqlHelper.ExecuteNonQuery(Database.ConnectionString, "course_files_Delete", course_files_ID);
            return course_files_ID;
        }
        catch (Exception ex)
        {

            return -1;
        }
    }

    public static DataTable SelectAll()
    {
        try
        {
            return SqlHelper.ExecuteDataset(Database.ConnectionString, "course_files_Select", 0).Tables[0];

        }
        catch (Exception ex)
        {

            return null;
        }
    }

    public static course_files_DT SelectByID(int course_files_ID)
    {
        try
        {
            SqlDataReader drTableName;
            course_files_DT oInfo_course_files_DT = new course_files_DT();
            if (course_files_ID > 0)
            {


                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "course_files_Select", course_files_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_course_files_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
            }
            return oInfo_course_files_DT;
        }
        catch (Exception ex)
        {

            return null;
        }
    }
    #endregion


}

