//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		course_DT
// Date Generated:	02-08-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class course_DT
    {
        public enum Enum_course_DT
        {
            id, course_id, course_place, emp_no, created_by, duration, refrences, inbox_id, prog_id, track_id, course_cost, last_register_date, organization, comments, candidate_criteria, refrance_file, start_date, end_date, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_place;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 emp_no;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 created_by;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 duration;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 refrences;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 inbox_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 prog_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 track_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Decimal course_cost;
		
		/// <summary>
		/// 
		/// </summary>
		public String last_register_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String organization;
		
		/// <summary>
		/// 
		/// </summary>
		public String comments;
		
		/// <summary>
		/// 
		/// </summary>
		public String candidate_criteria;
		
		/// <summary>
		/// 
		/// </summary>
		public String refrance_file;
		
		/// <summary>
		/// 
		/// </summary>
		public String start_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String end_date;
		
    }

