//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT-B51303A24F\Administrator using Mcit Generator
// Class Name:		course_employee_DT
// Date Generated:	19-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class course_employee_DT
    {
        public enum Enum_course_employee_DT
        {
            id, course_id, emp_id, course_details_id, is_admin_approved, status, comment, converted_to_course, rejected_reason_id,admin_descion,result,result_file
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 emp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_details_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Boolean is_admin_approved;
		
		/// <summary>
		/// 
		/// </summary>
		public String status;

        public String comment;

        public Int32 converted_to_course;
        public Int32 rejected_reason_id;
        public Int32 admin_descion;
        public Int32 result;
        public String result_file;
		
    }

