//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT-B51303A24F\Administrator using Mcit Generator
// Class Name:		course_files_DT
// Date Generated:	29-01-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class course_files_DT
    {
        public enum Enum_course_files_DT
        {
            id, course_id, file_path, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String file_path;
		
    }

