//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Course_Programs_DT
// Date Generated:	24-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Course_Programs_DT
    {
        public enum Enum_Course_Programs_DT
        {
            prog_id, prog_name, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 prog_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String prog_name;
		
    }

