//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT-B51303A24F\Administrator using Mcit Generator
// Class Name:		course_details_DT
// Date Generated:	29-01-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class course_details_DT
    {
        public enum Enum_course_details_DT
        {
            id, course_id, start_date, end_date, place, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String start_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String end_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String place;
		
    }

