//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Course_Tracks_DT
// Date Generated:	24-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Course_Tracks_DT
    {
        public enum Enum_Course_Tracks_DT
        {
            id, course_id, track_name, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String track_name;
		
    }

