//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Courses_DT
// Date Generated:	01-08-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Courses_DT
    {
        public enum Enum_Courses_DT
        {
            course_id, prog_id, course_name, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 prog_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String course_name;
		
    }

