//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Course_Places_DT
// Date Generated:	25-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Course_Places_DT
    {
        public enum Enum_Course_Places_DT
        {
            place_id, place_desc, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 place_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String place_desc;
		
    }

