//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Training_Plan_DT
// Date Generated:	23-11-2014
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Training_Plan_DT
    {
        public enum Enum_Training_Plan_DT
        {
            id, course_id, emp_id, isapproved, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 course_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 emp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 isapproved;
		
    }

