//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Main_Categories_DB
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Review_Main_Categories_DB
    {

        #region "Private methods"

        private static Review_Main_Categories_DT FillInfoObject(SqlDataReader dr)
        {

           Review_Main_Categories_DT obj_Review_Main_Categories_DT = new Review_Main_Categories_DT();

           
		obj_Review_Main_Categories_DT.id = Convert.ToInt32(dr[Review_Main_Categories_DT.Enum_Review_Main_Categories_DT.id.ToString()]);
		obj_Review_Main_Categories_DT.group_id = dr[Review_Main_Categories_DT.Enum_Review_Main_Categories_DT.group_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Main_Categories_DT.Enum_Review_Main_Categories_DT.group_id.ToString()]);
		obj_Review_Main_Categories_DT.Name = dr[Review_Main_Categories_DT.Enum_Review_Main_Categories_DT.Name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Main_Categories_DT.Enum_Review_Main_Categories_DT.Name.ToString()]);

           return obj_Review_Main_Categories_DT;
        }

        private static SqlParameter[] GetParameters(Review_Main_Categories_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[3];
           
			
        

        parms[0] = new SqlParameter(Review_Main_Categories_DT.Enum_Review_Main_Categories_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Review_Main_Categories_DT.Enum_Review_Main_Categories_DT.group_id.ToString(), obj.group_id);

        parms[2] = new SqlParameter(Review_Main_Categories_DT.Enum_Review_Main_Categories_DT.Name.ToString(), obj.Name);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(Review_Main_Categories_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Review_Main_Categories_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Review_Main_Categories_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Review_Main_Categories_Delete", Review_Main_Categories_ID);
                return Review_Main_Categories_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Review_Main_Categories_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static Review_Main_Categories_DT SelectByID(int Review_Main_Categories_ID)
        {
            try
            {
              if (Review_Main_Categories_ID > 0)
                {
                SqlDataReader drTableName;
                Review_Main_Categories_DT oInfo_Review_Main_Categories_DT = new Review_Main_Categories_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Review_Main_Categories_Select", Review_Main_Categories_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Review_Main_Categories_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Review_Main_Categories_DT;
               }
                else
                    return new Review_Main_Categories_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

