//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Track_Emp_DB
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Review_Track_Emp_DB
    {

        #region "Private methods"

        private static Review_Track_Emp_DT FillInfoObject(SqlDataReader dr)
        {

           Review_Track_Emp_DT obj_Review_Track_Emp_DT = new Review_Track_Emp_DT();

           
		obj_Review_Track_Emp_DT.ID = Convert.ToInt32(dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.ID.ToString()]);
		obj_Review_Track_Emp_DT.Review_id = dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Review_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Review_id.ToString()]);
		obj_Review_Track_Emp_DT.Emp_ID = dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Emp_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Emp_ID.ToString()]);
		obj_Review_Track_Emp_DT.Review_Status = dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Review_Status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Review_Status.ToString()]);
		obj_Review_Track_Emp_DT.Type_Track_emp = dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Type_Track_emp.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Type_Track_emp.ToString()]);

           return obj_Review_Track_Emp_DT;
        }

        private static SqlParameter[] GetParameters(Review_Track_Emp_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[5];
           
			
        

        parms[0] = new SqlParameter(Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.ID.ToString(), obj.ID);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Review_id.ToString(), obj.Review_id);

        parms[2] = new SqlParameter(Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Emp_ID.ToString(), obj.Emp_ID);

        parms[3] = new SqlParameter(Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Review_Status.ToString(), obj.Review_Status);

        parms[4] = new SqlParameter(Review_Track_Emp_DT.Enum_Review_Track_Emp_DT.Type_Track_emp.ToString(), obj.Type_Track_emp);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(Review_Track_Emp_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Review_Track_Emp_Save", parms);

             	    obj.ID = Convert.ToInt32(parms[0].Value) ; 

           return obj.ID ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Review_Track_Emp_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Review_Track_Emp_Delete", Review_Track_Emp_ID);
                return Review_Track_Emp_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Review_Track_Emp_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static Review_Track_Emp_DT SelectByID(int Review_Track_Emp_ID)
        {
            try
            {
              if (Review_Track_Emp_ID > 0)
                {
                SqlDataReader drTableName;
                Review_Track_Emp_DT oInfo_Review_Track_Emp_DT = new Review_Track_Emp_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Review_Track_Emp_Select", Review_Track_Emp_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Review_Track_Emp_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Review_Track_Emp_DT;
               }
                else
                    return new Review_Track_Emp_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion





        public static DataTable Select_bulliten_new(int Emp_ID,int Review_Status)
        {
            try
            {
                return SqlHelper.ExecuteDataset(Database.ConnectionString, "Review_new", Emp_ID,Review_Status ).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
        }


        public static DataTable Select_bulliten_closed(int Emp_ID, int Review_Status)
        {
            try
            {
                return SqlHelper.ExecuteDataset(Database.ConnectionString, "Review_closed", Emp_ID, Review_Status).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
        }


    }

