//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Track_Manager_DB
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


public static class Review_Track_Manager_DB
{

    #region "Private methods"

    private static Review_Track_Manager_DT FillInfoObject(SqlDataReader dr)
    {

        Review_Track_Manager_DT obj_Review_Track_Manager_DT = new Review_Track_Manager_DT();


        obj_Review_Track_Manager_DT.Review_id = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Review_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Review_id.ToString()]);
        obj_Review_Track_Manager_DT.status = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.status.ToString()]);
        obj_Review_Track_Manager_DT.IS_New_Mail = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.IS_New_Mail.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.IS_New_Mail.ToString()]);
        obj_Review_Track_Manager_DT.Have_Follow = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Have_Follow.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Have_Follow.ToString()]);
        obj_Review_Track_Manager_DT.Have_Visa = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Have_Visa.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Have_Visa.ToString()]);
        obj_Review_Track_Manager_DT.IS_Old_Mail = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.IS_Old_Mail.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.IS_Old_Mail.ToString()]);
        obj_Review_Track_Manager_DT.pmp_id = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.pmp_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.pmp_id.ToString()]);
        obj_Review_Track_Manager_DT.parent_pmp_id = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.parent_pmp_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.parent_pmp_id.ToString()]);
        obj_Review_Track_Manager_DT.Type_Track = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Type_Track.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Type_Track.ToString()]);
        obj_Review_Track_Manager_DT.All_visa_sent = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.All_visa_sent.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.All_visa_sent.ToString()]);
        obj_Review_Track_Manager_DT.Visa_Desc = dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Visa_Desc.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Visa_Desc.ToString()]);

        return obj_Review_Track_Manager_DT;
    }

    private static SqlParameter[] GetParameters(Review_Track_Manager_DT obj)
    {
        SqlParameter[] parms = new SqlParameter[11];



        parms[0] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Review_id.ToString(), obj.Review_id);

        parms[1] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.status.ToString(), obj.status);

        parms[2] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.IS_New_Mail.ToString(), obj.IS_New_Mail);

        parms[3] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Have_Follow.ToString(), obj.Have_Follow);

        parms[4] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Have_Visa.ToString(), obj.Have_Visa);

        parms[5] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.IS_Old_Mail.ToString(), obj.IS_Old_Mail);

        parms[6] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.pmp_id.ToString(), obj.pmp_id);

        parms[7] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.parent_pmp_id.ToString(), obj.parent_pmp_id);

        parms[8] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Type_Track.ToString(), obj.Type_Track);

        parms[9] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.All_visa_sent.ToString(), obj.All_visa_sent);

        parms[10] = new SqlParameter(Review_Track_Manager_DT.Enum_Review_Track_Manager_DT.Visa_Desc.ToString(), obj.Visa_Desc);

        return parms;
    }

    #endregion

    #region "DB methods"

    public static int Save(Review_Track_Manager_DT obj)
    {
        try
        {
            SqlParameter[] parms = GetParameters(obj);

            SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Review_Track_Manager_Save", parms);
            return Convert.ToInt32(parms[0].Value);

        }
        catch (Exception ex)
        {

            return -1;
        }
    }

    public static int Delete(int Review_Track_Manager_ID)
    {
        try
        {
            SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Review_Track_Manager_Delete", Review_Track_Manager_ID);
            return Review_Track_Manager_ID;
        }
        catch (Exception ex)
        {

            return -1;
        }
    }

    public static DataTable SelectAll()
    {
        try
        {
            return SqlHelper.ExecuteDataset(Database.ConnectionString, "Review_Track_Manager_Select", 0).Tables[0];

        }
        catch (Exception ex)
        {

            return null;
        }
    }

    public static Review_Track_Manager_DT SelectByID(int Review_Track_Manager_ID)
    {
        try
        {
            if (Review_Track_Manager_ID > 0)
            {
                SqlDataReader drTableName;
                Review_Track_Manager_DT oInfo_Review_Track_Manager_DT = new Review_Track_Manager_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Review_Track_Manager_Select", Review_Track_Manager_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Review_Track_Manager_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Review_Track_Manager_DT;
            }
            else
                return new Review_Track_Manager_DT();
        }
        catch (Exception ex)
        {

            return null;
        }
    }
    #endregion


}

