//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_sub_categories_DB
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Review_sub_categories_DB
    {

        #region "Private methods"

        private static Review_sub_categories_DT FillInfoObject(SqlDataReader dr)
        {

           Review_sub_categories_DT obj_Review_sub_categories_DT = new Review_sub_categories_DT();

           
		obj_Review_sub_categories_DT.id = Convert.ToInt32(dr[Review_sub_categories_DT.Enum_Review_sub_categories_DT.id.ToString()]);
		obj_Review_sub_categories_DT.main_id = dr[Review_sub_categories_DT.Enum_Review_sub_categories_DT.main_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_sub_categories_DT.Enum_Review_sub_categories_DT.main_id.ToString()]);
		obj_Review_sub_categories_DT.name = dr[Review_sub_categories_DT.Enum_Review_sub_categories_DT.name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_sub_categories_DT.Enum_Review_sub_categories_DT.name.ToString()]);

           return obj_Review_sub_categories_DT;
        }

        private static SqlParameter[] GetParameters(Review_sub_categories_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[3];
           
			
        

        parms[0] = new SqlParameter(Review_sub_categories_DT.Enum_Review_sub_categories_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Review_sub_categories_DT.Enum_Review_sub_categories_DT.main_id.ToString(), obj.main_id);

        parms[2] = new SqlParameter(Review_sub_categories_DT.Enum_Review_sub_categories_DT.name.ToString(), obj.name);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(Review_sub_categories_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Review_sub_categories_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Review_sub_categories_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Review_sub_categories_Delete", Review_sub_categories_ID);
                return Review_sub_categories_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Review_sub_categories_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static Review_sub_categories_DT SelectByID(int Review_sub_categories_ID)
        {
            try
            {
              if (Review_sub_categories_ID > 0)
                {
                SqlDataReader drTableName;
                Review_sub_categories_DT oInfo_Review_sub_categories_DT = new Review_sub_categories_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Review_sub_categories_Select", Review_sub_categories_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Review_sub_categories_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Review_sub_categories_DT;
               }
                else
                    return new Review_sub_categories_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

