//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\tmeltaweel using Mcit Generator
// Class Name:		Review_Visa_DB
// Date Generated:	08-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Review_Visa_DB
    {

        #region "Private methods"

        private static Review_Visa_DT FillInfoObject(SqlDataReader dr)
        {

           Review_Visa_DT obj_Review_Visa_DT = new Review_Visa_DT();

           
		obj_Review_Visa_DT.Visa_Id = Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Id.ToString()]);
		obj_Review_Visa_DT.Review_ID = dr[Review_Visa_DT.Enum_Review_Visa_DT.Review_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Review_ID.ToString()]);
		obj_Review_Visa_DT.Important_Degree = dr[Review_Visa_DT.Enum_Review_Visa_DT.Important_Degree.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Important_Degree.ToString()]);
		obj_Review_Visa_DT.Dept_ID = dr[Review_Visa_DT.Enum_Review_Visa_DT.Dept_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Dept_ID.ToString()]);
		obj_Review_Visa_DT.Emp_ID = dr[Review_Visa_DT.Enum_Review_Visa_DT.Emp_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Emp_ID.ToString()]);
		obj_Review_Visa_DT.Visa_Satus = dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Satus.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Satus.ToString()]);
		obj_Review_Visa_DT.Follow_Up_Dept_ID = dr[Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Dept_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Dept_ID.ToString()]);
		obj_Review_Visa_DT.Follow_Up_Emp_ID = dr[Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Emp_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Emp_ID.ToString()]);
		obj_Review_Visa_DT.Visa_Goal_ID = dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Goal_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Goal_ID.ToString()]);
		obj_Review_Visa_DT.mail_sent = dr[Review_Visa_DT.Enum_Review_Visa_DT.mail_sent.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Review_Visa_DT.Enum_Review_Visa_DT.mail_sent.ToString()]);
		obj_Review_Visa_DT.Visa_Desc = dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Desc.ToString()] == DBNull.Value ? null : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Desc.ToString()]);
		obj_Review_Visa_DT.Visa_date = dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_date.ToString()]);
		obj_Review_Visa_DT.Important_Degree_Txt = dr[Review_Visa_DT.Enum_Review_Visa_DT.Important_Degree_Txt.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.Important_Degree_Txt.ToString()]);
		obj_Review_Visa_DT.Dept_ID_Txt = dr[Review_Visa_DT.Enum_Review_Visa_DT.Dept_ID_Txt.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.Dept_ID_Txt.ToString()]);
		obj_Review_Visa_DT.Emp_ID_Txt = dr[Review_Visa_DT.Enum_Review_Visa_DT.Emp_ID_Txt.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.Emp_ID_Txt.ToString()]);
		obj_Review_Visa_DT.Visa_Period = dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Period.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.Visa_Period.ToString()]);
		obj_Review_Visa_DT.Follow_Up_Notes = dr[Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Notes.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Notes.ToString()]);
		obj_Review_Visa_DT.saving_file = dr[Review_Visa_DT.Enum_Review_Visa_DT.saving_file.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.saving_file.ToString()]);
		obj_Review_Visa_DT.Dead_Line_DT = dr[Review_Visa_DT.Enum_Review_Visa_DT.Dead_Line_DT.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Review_Visa_DT.Enum_Review_Visa_DT.Dead_Line_DT.ToString()]);

           return obj_Review_Visa_DT;
        }

        private static SqlParameter[] GetParameters(Review_Visa_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[19];
           
			
        

        parms[0] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Visa_Id.ToString(), obj.Visa_Id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Review_ID.ToString(), obj.Review_ID);

        parms[2] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Important_Degree.ToString(), obj.Important_Degree);

        parms[3] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Dept_ID.ToString(), obj.Dept_ID);

        parms[4] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Emp_ID.ToString(), obj.Emp_ID);

        parms[5] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Visa_Satus.ToString(), obj.Visa_Satus);

        parms[6] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Dept_ID.ToString(), obj.Follow_Up_Dept_ID);

        parms[7] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Emp_ID.ToString(), obj.Follow_Up_Emp_ID);

        parms[8] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Visa_Goal_ID.ToString(), obj.Visa_Goal_ID);

        parms[9] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.mail_sent.ToString(), obj.mail_sent);

        parms[10] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Visa_Desc.ToString(), obj.Visa_Desc);

        parms[11] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Visa_date.ToString(), obj.Visa_date);

        parms[12] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Important_Degree_Txt.ToString(), obj.Important_Degree_Txt);

        parms[13] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Dept_ID_Txt.ToString(), obj.Dept_ID_Txt);

        parms[14] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Emp_ID_Txt.ToString(), obj.Emp_ID_Txt);

        parms[15] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Visa_Period.ToString(), obj.Visa_Period);

        parms[16] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Follow_Up_Notes.ToString(), obj.Follow_Up_Notes);

        parms[17] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.saving_file.ToString(), obj.saving_file);

        parms[18] = new SqlParameter(Review_Visa_DT.Enum_Review_Visa_DT.Dead_Line_DT.ToString(), obj.Dead_Line_DT);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(Review_Visa_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Review_Visa_Save", parms);

             	    obj.Visa_Id = Convert.ToInt32(parms[0].Value) ; 

           return obj.Visa_Id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Review_Visa_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Review_Visa_Delete", Review_Visa_ID);
                return Review_Visa_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Review_Visa_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static Review_Visa_DT SelectByID(int Review_Visa_ID)
        {
            try
            {
              if (Review_Visa_ID > 0)
                {
                SqlDataReader drTableName;
                Review_Visa_DT oInfo_Review_Visa_DT = new Review_Visa_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Review_Visa_Select", Review_Visa_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Review_Visa_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Review_Visa_DT;
               }
                else
                    return new Review_Visa_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

