//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\malmeligi using Mcit Generator
// Class Name:		proj_services_DB
// Date Generated:	14-05-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class proj_services_DB
    {

        #region "Private methods"

        private static proj_services_DT FillInfoObject(SqlDataReader dr)
        {

           proj_services_DT obj_proj_services_DT = new proj_services_DT();

           
		obj_proj_services_DT.id = Convert.ToInt32(dr[proj_services_DT.Enum_proj_services_DT.id.ToString()]);
		obj_proj_services_DT.proj_id = dr[proj_services_DT.Enum_proj_services_DT.proj_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[proj_services_DT.Enum_proj_services_DT.proj_id.ToString()]);
		obj_proj_services_DT.proj_citizen_service = dr[proj_services_DT.Enum_proj_services_DT.proj_citizen_service.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[proj_services_DT.Enum_proj_services_DT.proj_citizen_service.ToString()]);
		obj_proj_services_DT.proj_gov_service = dr[proj_services_DT.Enum_proj_services_DT.proj_gov_service.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[proj_services_DT.Enum_proj_services_DT.proj_gov_service.ToString()]);

           return obj_proj_services_DT;
        }

        private static SqlParameter[] GetParameters(proj_services_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[4];
           
			
        

        parms[0] = new SqlParameter(proj_services_DT.Enum_proj_services_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(proj_services_DT.Enum_proj_services_DT.proj_id.ToString(), obj.proj_id);

        parms[2] = new SqlParameter(proj_services_DT.Enum_proj_services_DT.proj_citizen_service.ToString(), obj.proj_citizen_service);

        parms[3] = new SqlParameter(proj_services_DT.Enum_proj_services_DT.proj_gov_service.ToString(), obj.proj_gov_service);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(proj_services_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "proj_services_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int proj_services_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "proj_services_Delete", proj_services_ID);
                return proj_services_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "proj_services_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static proj_services_DT SelectByID(int proj_services_ID)
        {
            try
            {
              if (proj_services_ID > 0)
                {
                SqlDataReader drTableName;
                proj_services_DT oInfo_proj_services_DT = new proj_services_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "proj_services_Select", proj_services_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_proj_services_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_proj_services_DT;
               }
                else
                    return new proj_services_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

