//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Commission_Visa_Emp_DT
// Date Generated:	11-11-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Commission_Visa_Emp_DT
    {
        public enum Enum_Commission_Visa_Emp_DT
        {
            Visa_Emp_ID, Visa_Id, Emp_ID, Sender_ID, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Visa_Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Visa_Id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Sender_ID;
		
    }

