//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Commission_Track_Emp_DT
// Date Generated:	11-11-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Commission_Track_Emp_DT
    {
        public enum Enum_Commission_Track_Emp_DT
        {
            ID, Commission_id, Emp_ID, Commission_Status, Type_Track_emp, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Commission_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Emp_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Commission_Status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Type_Track_emp;
		
    }

