//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\malmeligi using Mcit Generator
// Class Name:		Outbox_Visa_Follows_DT
// Date Generated:	23-01-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Outbox_Visa_Follows_DT
    {
        public enum Enum_Outbox_Visa_Follows_DT
        {
            Follow_ID, Outbox_ID, Visa_Emp_id, entery_pmp_id, Type_Follow, File_data, Descrption, Date, File_name, File_ext, time_follow, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Follow_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Outbox_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Visa_Emp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 entery_pmp_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Type_Follow;
		
		/// <summary>
		/// 
		/// </summary>
		public Byte[] File_data;
		
		/// <summary>
		/// 
		/// </summary>
		public String Descrption;
		
		/// <summary>
		/// 
		/// </summary>
		public String Date;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_ext;
		
		/// <summary>
		/// 
		/// </summary>
		public String time_follow;
		
    }

