//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\Mabdeltwab using Mcit Generator
// Class Name:		RollSearch_SP
// Date Generated:	13-01-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;



    public class RollSearch_SP
    {
        public enum Enum_RollSearch_SP
        {
            RollDate, AdminUser, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public DateTime RollDate;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 AdminUser;
		

       #region "Private methods"

      
        private static SqlParameter[] GetParameters(RollSearch_SP obj)
        {
            SqlParameter[] parms = new SqlParameter[2];
           
			

        parms[0] = new SqlParameter(RollSearch_SP.Enum_RollSearch_SP.RollDate.ToString(), obj.RollDate);

        parms[1] = new SqlParameter(RollSearch_SP.Enum_RollSearch_SP.AdminUser.ToString(), obj.AdminUser);
            
            return parms;
        }

        #endregion

       #region "DB methods"

        public static DataTable  Get_DataTable(RollSearch_SP obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

          return SqlHelper.ExecuteDataset(Database.ConnectionString, CommandType.StoredProcedure, "RollSearch", parms).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
        }
     #endregion
    }

