//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\mmabdelmalek using Mcit Generator
// Class Name:		Select_Active_Room_By_Participant2_SP
// Date Generated:	30-09-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;



    public class Select_Active_Room_By_Participant2_SP
    {
        public enum Enum_Select_Active_Room_By_Participant2_SP
        {
            Participant2, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 Participant2;
		

       #region "Private methods"

      
        private static SqlParameter[] GetParameters(Select_Active_Room_By_Participant2_SP obj)
        {
            SqlParameter[] parms = new SqlParameter[1];
           
			

        parms[0] = new SqlParameter(Select_Active_Room_By_Participant2_SP.Enum_Select_Active_Room_By_Participant2_SP.Participant2.ToString(), obj.Participant2);
            
            return parms;
        }

        #endregion

       #region "DB methods"

        public static DataTable  Get_DataTable(Select_Active_Room_By_Participant2_SP obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

          return SqlHelper.ExecuteDataset(Database.ConnectionString, CommandType.StoredProcedure, "Select_Active_Room_By_Participant2", parms).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
        }
     #endregion
    }

