//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmghaith using Mcit Generator
// Class Name:		Employee_Ex_Training_DB
// Date Generated:	01-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


public static class Employee_Ex_Training_DB
{

    #region "Private methods"

    private static Employee_Ex_Training_DT FillInfoObject(SqlDataReader dr)
    {

        Employee_Ex_Training_DT obj_Employee_Ex_Training_DT = new Employee_Ex_Training_DT();


        obj_Employee_Ex_Training_DT.id = Convert.ToInt32(dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.id.ToString()]);
        obj_Employee_Ex_Training_DT.pmp_id = dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.pmp_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.pmp_id.ToString()]);
        obj_Employee_Ex_Training_DT.course_name = dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.course_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.course_name.ToString()]);
        obj_Employee_Ex_Training_DT.start_date = dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.start_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.start_date.ToString()]);
        obj_Employee_Ex_Training_DT.end_date = dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.end_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.end_date.ToString()]);

        return obj_Employee_Ex_Training_DT;
    }

    private static SqlParameter[] GetParameters(Employee_Ex_Training_DT obj)
    {
        SqlParameter[] parms = new SqlParameter[5];




        parms[0] = new SqlParameter(Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.pmp_id.ToString(), obj.pmp_id);

        parms[2] = new SqlParameter(Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.course_name.ToString(), obj.course_name);

        parms[3] = new SqlParameter(Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.start_date.ToString(), obj.start_date);

        parms[4] = new SqlParameter(Employee_Ex_Training_DT.Enum_Employee_Ex_Training_DT.end_date.ToString(), obj.end_date);

        return parms;
    }

    #endregion

    #region "DB methods"

    public static int Save(Employee_Ex_Training_DT obj)
    {
        try
        {
            SqlParameter[] parms = GetParameters(obj);

            SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Employee_Ex_Training_Save", parms);

            obj.id = Convert.ToInt32(parms[0].Value);

            return obj.id;
        }
        catch (Exception ex)
        {

            return -1;
        }
    }

    public static int Delete(int Employee_Ex_Training_ID)
    {
        try
        {
            SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Employee_Ex_Training_Delete", Employee_Ex_Training_ID);
            return Employee_Ex_Training_ID;
        }
        catch (Exception ex)
        {

            return -1;
        }
    }

    public static DataTable SelectAll()
    {
        try
        {
            return SqlHelper.ExecuteDataset(Database.ConnectionString, "Employee_Ex_Training_Select", 0).Tables[0];

        }
        catch (Exception ex)
        {

            return null;
        }
    }

    public static Employee_Ex_Training_DT SelectByID(int Employee_Ex_Training_ID)
    {
        try
        {
            if (Employee_Ex_Training_ID > 0)
            {
                SqlDataReader drTableName;
                Employee_Ex_Training_DT oInfo_Employee_Ex_Training_DT = new Employee_Ex_Training_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Employee_Ex_Training_Select", Employee_Ex_Training_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Employee_Ex_Training_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Employee_Ex_Training_DT;
            }
            else
                return new Employee_Ex_Training_DT();
        }
        catch (Exception ex)
        {

            return null;
        }
    }



    public static DataTable SelectByPmp_id(int pmp_id)
    {
        try
        {
            return SqlHelper.ExecuteDataset(Database.ConnectionString, "Employee_Ex_Training_Select_by_pmp_id", pmp_id).Tables[0];

        }
        catch (Exception ex)
        {

            return null;
        }




    }
}
            
        
	#endregion


