//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		Stages_DB
// Date Generated:	30-01-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Stages_DB
    {

        #region "Private methods"

        private static Stages_DT FillInfoObject(SqlDataReader dr)
        {

           Stages_DT obj_Stages_DT = new Stages_DT();

           
		obj_Stages_DT.id = Convert.ToInt32(dr[Stages_DT.Enum_Stages_DT.id.ToString()]);
		obj_Stages_DT.stage_title = dr[Stages_DT.Enum_Stages_DT.stage_title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Stages_DT.Enum_Stages_DT.stage_title.ToString()]);

           return obj_Stages_DT;
        }

        private static SqlParameter[] GetParameters(Stages_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[2];
           
			
        

        parms[0] = new SqlParameter(Stages_DT.Enum_Stages_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Stages_DT.Enum_Stages_DT.stage_title.ToString(), obj.stage_title);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(Stages_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Stages_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Stages_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Stages_Delete", Stages_ID);
                return Stages_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Stages_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static Stages_DT SelectByID(int Stages_ID)
        {
            try
            {
              if (Stages_ID > 0)
                {
                SqlDataReader drTableName;
                Stages_DT oInfo_Stages_DT = new Stages_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Stages_Select", Stages_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Stages_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Stages_DT;
               }
                else
                    return new Stages_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

