//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Commission_Visa_Emp_DB
// Date Generated:	11-11-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Commission_Visa_Emp_DB
    {

        #region "Private methods"

        private static Commission_Visa_Emp_DT FillInfoObject(SqlDataReader dr)
        {

           Commission_Visa_Emp_DT obj_Commission_Visa_Emp_DT = new Commission_Visa_Emp_DT();

           
		obj_Commission_Visa_Emp_DT.Visa_Emp_ID = Convert.ToInt32(dr[Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Visa_Emp_ID.ToString()]);
		obj_Commission_Visa_Emp_DT.Visa_Id = dr[Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Visa_Id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Visa_Id.ToString()]);
		obj_Commission_Visa_Emp_DT.Emp_ID = dr[Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Emp_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Emp_ID.ToString()]);
		obj_Commission_Visa_Emp_DT.Sender_ID = dr[Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Sender_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Sender_ID.ToString()]);

           return obj_Commission_Visa_Emp_DT;
        }

        private static SqlParameter[] GetParameters(Commission_Visa_Emp_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[4];
           
			
        

        parms[0] = new SqlParameter(Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Visa_Emp_ID.ToString(), obj.Visa_Emp_ID);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Visa_Id.ToString(), obj.Visa_Id);

        parms[2] = new SqlParameter(Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Emp_ID.ToString(), obj.Emp_ID);

        parms[3] = new SqlParameter(Commission_Visa_Emp_DT.Enum_Commission_Visa_Emp_DT.Sender_ID.ToString(), obj.Sender_ID);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(Commission_Visa_Emp_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Commission_Visa_Emp_Save", parms);

             	    obj.Visa_Emp_ID = Convert.ToInt32(parms[0].Value) ; 

           return obj.Visa_Emp_ID ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Commission_Visa_Emp_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Commission_Visa_Emp_Delete", Commission_Visa_Emp_ID);
                return Commission_Visa_Emp_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Commission_Visa_Emp_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static Commission_Visa_Emp_DT SelectByID(int Commission_Visa_Emp_ID)
        {
            try
            {
              if (Commission_Visa_Emp_ID > 0)
                {
                SqlDataReader drTableName;
                Commission_Visa_Emp_DT oInfo_Commission_Visa_Emp_DT = new Commission_Visa_Emp_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Commission_Visa_Emp_Select", Commission_Visa_Emp_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Commission_Visa_Emp_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Commission_Visa_Emp_DT;
               }
                else
                    return new Commission_Visa_Emp_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

