//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\MElshahed using Mcit Generator
// Class Name:		Commission_Track_Emp_DB
// Date Generated:	11-11-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Commission_Track_Emp_DB
    {

        #region "Private methods"

        private static Commission_Track_Emp_DT FillInfoObject(SqlDataReader dr)
        {

           Commission_Track_Emp_DT obj_Commission_Track_Emp_DT = new Commission_Track_Emp_DT();

           
		obj_Commission_Track_Emp_DT.ID = Convert.ToInt32(dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.ID.ToString()]);
		obj_Commission_Track_Emp_DT.Commission_id = dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Commission_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Commission_id.ToString()]);
		obj_Commission_Track_Emp_DT.Emp_ID = dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Emp_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Emp_ID.ToString()]);
		obj_Commission_Track_Emp_DT.Commission_Status = dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Commission_Status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Commission_Status.ToString()]);
		obj_Commission_Track_Emp_DT.Type_Track_emp = dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Type_Track_emp.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Type_Track_emp.ToString()]);

           return obj_Commission_Track_Emp_DT;
        }

        private static SqlParameter[] GetParameters(Commission_Track_Emp_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[5];
           
			
        

        parms[0] = new SqlParameter(Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.ID.ToString(), obj.ID);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Commission_id.ToString(), obj.Commission_id);

        parms[2] = new SqlParameter(Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Emp_ID.ToString(), obj.Emp_ID);

        parms[3] = new SqlParameter(Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Commission_Status.ToString(), obj.Commission_Status);

        parms[4] = new SqlParameter(Commission_Track_Emp_DT.Enum_Commission_Track_Emp_DT.Type_Track_emp.ToString(), obj.Type_Track_emp);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(Commission_Track_Emp_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Commission_Track_Emp_Save", parms);

             	    obj.ID = Convert.ToInt32(parms[0].Value) ; 

           return obj.ID ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Commission_Track_Emp_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Commission_Track_Emp_Delete", Commission_Track_Emp_ID);
                return Commission_Track_Emp_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Commission_Track_Emp_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static DataTable Commission_Track_Emp_update(int comm_id)
        {
            try
            {
                return SqlHelper.ExecuteDataset(Database.ConnectionString, "Commission_Track_Emp_update", comm_id ).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
        }
        public static Commission_Track_Emp_DT SelectByID(int Commission_Track_Emp_ID)
        {
            try
            {
              if (Commission_Track_Emp_ID > 0)
                {
                SqlDataReader drTableName;
                Commission_Track_Emp_DT oInfo_Commission_Track_Emp_DT = new Commission_Track_Emp_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Commission_Track_Emp_Select", Commission_Track_Emp_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_Commission_Track_Emp_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_Commission_Track_Emp_DT;
               }
                else
                    return new Commission_Track_Emp_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

