//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\malmeligi using Mcit Generator
// Class Name:		Outbox_Visa_Follows_DB
// Date Generated:	23-01-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Outbox_Visa_Follows_DB
    {

        #region "Private methods"

        private static Outbox_Visa_Follows_DT FillInfoObject(SqlDataReader dr)
        {

           Outbox_Visa_Follows_DT obj_Outbox_Visa_Follows_DT = new Outbox_Visa_Follows_DT();

           
		obj_Outbox_Visa_Follows_DT.Follow_ID = Convert.ToInt32(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Follow_ID.ToString()]);
		obj_Outbox_Visa_Follows_DT.Outbox_ID = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Outbox_ID.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Outbox_ID.ToString()]);
		obj_Outbox_Visa_Follows_DT.Visa_Emp_id = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Visa_Emp_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Visa_Emp_id.ToString()]);
		obj_Outbox_Visa_Follows_DT.entery_pmp_id = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.entery_pmp_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.entery_pmp_id.ToString()]);
		obj_Outbox_Visa_Follows_DT.Type_Follow = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Type_Follow.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Type_Follow.ToString()]);
        obj_Outbox_Visa_Follows_DT.File_data = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_data.ToString()] == DBNull.Value ? null : (Byte[])(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_data.ToString()]);
        obj_Outbox_Visa_Follows_DT.Descrption = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Descrption.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Descrption.ToString()]);
		obj_Outbox_Visa_Follows_DT.Date = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Date.ToString()]);
		obj_Outbox_Visa_Follows_DT.File_name = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_name.ToString()]);
		obj_Outbox_Visa_Follows_DT.File_ext = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_ext.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_ext.ToString()]);
		obj_Outbox_Visa_Follows_DT.time_follow = dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.time_follow.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.time_follow.ToString()]);

           return obj_Outbox_Visa_Follows_DT;
        }

        private static SqlParameter[] GetParameters(Outbox_Visa_Follows_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[8];
           
			
        

        parms[0] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Follow_ID.ToString(), obj.Follow_ID);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Outbox_ID.ToString(), obj.Outbox_ID);

        parms[2] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Visa_Emp_id.ToString(), obj.Visa_Emp_id);

        parms[3] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.entery_pmp_id.ToString(), obj.entery_pmp_id);

        parms[4] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Type_Follow.ToString(), obj.Type_Follow);

        //parms[5] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_data.ToString(), obj.File_data);

        parms[5] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Descrption.ToString(), obj.Descrption);

        parms[6] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.Date.ToString(), obj.Date);

        //parms[8] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_name.ToString(), obj.File_name);

        //parms[9] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.File_ext.ToString(), obj.File_ext);

        parms[7] = new SqlParameter(Outbox_Visa_Follows_DT.Enum_Outbox_Visa_Follows_DT.time_follow.ToString(), obj.time_follow);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(Outbox_Visa_Follows_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Outbox_Visa_Follows_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Outbox_Visa_Follows_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Outbox_Visa_Follows_Delete", Outbox_Visa_Follows_ID);
                return Outbox_Visa_Follows_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Outbox_Visa_Follows_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static Outbox_Visa_Follows_DT SelectByID(int Outbox_Visa_Follows_ID)
        {
            try
            {
                SqlDataReader drTableName;
                Outbox_Visa_Follows_DT oInfo_Outbox_Visa_Follows_DT = new Outbox_Visa_Follows_DT();
                if (Outbox_Visa_Follows_ID > 0)
                {
                    drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Outbox_Visa_Follows_Select", Outbox_Visa_Follows_ID);
                    if (drTableName != null)
                    {
                        while (drTableName.Read())
                        {
                            oInfo_Outbox_Visa_Follows_DT = FillInfoObject(drTableName);
                        }

                        drTableName.Close();
                    }
                }
                return oInfo_Outbox_Visa_Follows_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

