//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\malmeligi using Mcit Generator
// Class Name:		Outbox_Track_Manager_DB
// Date Generated:	24-01-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class Outbox_Track_Manager_DB
    {

        #region "Private methods"

        private static Outbox_Track_Manager_DT FillInfoObject(SqlDataReader dr)
        {

           Outbox_Track_Manager_DT obj_Outbox_Track_Manager_DT = new Outbox_Track_Manager_DT();

           
		obj_Outbox_Track_Manager_DT.Outbox_id = Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Outbox_id.ToString()]);
		obj_Outbox_Track_Manager_DT.status = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.status.ToString()]);
		obj_Outbox_Track_Manager_DT.IS_New_Mail = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.IS_New_Mail.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.IS_New_Mail.ToString()]);
		obj_Outbox_Track_Manager_DT.Have_Follow = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Have_Follow.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Have_Follow.ToString()]);
		obj_Outbox_Track_Manager_DT.Have_Visa = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Have_Visa.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Have_Visa.ToString()]);
		obj_Outbox_Track_Manager_DT.IS_Old_Mail = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.IS_Old_Mail.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.IS_Old_Mail.ToString()]);
		obj_Outbox_Track_Manager_DT.pmp_id = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.pmp_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.pmp_id.ToString()]);
		obj_Outbox_Track_Manager_DT.parent_pmp_id = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.parent_pmp_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.parent_pmp_id.ToString()]);
		obj_Outbox_Track_Manager_DT.Type_Track = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Type_Track.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Type_Track.ToString()]);
		obj_Outbox_Track_Manager_DT.All_visa_sent = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.All_visa_sent.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.All_visa_sent.ToString()]);
		obj_Outbox_Track_Manager_DT.Visa_Desc = dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Visa_Desc.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Visa_Desc.ToString()]);

           return obj_Outbox_Track_Manager_DT;
        }

        private static SqlParameter[] GetParameters(Outbox_Track_Manager_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[11];
           
			
        

        parms[0] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Outbox_id.ToString(), obj.Outbox_id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.status.ToString(), obj.status);

        parms[2] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.IS_New_Mail.ToString(), obj.IS_New_Mail);

        parms[3] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Have_Follow.ToString(), obj.Have_Follow);

        parms[4] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Have_Visa.ToString(), obj.Have_Visa);

        parms[5] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.IS_Old_Mail.ToString(), obj.IS_Old_Mail);

        parms[6] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.pmp_id.ToString(), obj.pmp_id);

        parms[7] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.parent_pmp_id.ToString(), obj.parent_pmp_id);

        parms[8] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Type_Track.ToString(), obj.Type_Track);

        parms[9] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.All_visa_sent.ToString(), obj.All_visa_sent);

        parms[10] = new SqlParameter(Outbox_Track_Manager_DT.Enum_Outbox_Track_Manager_DT.Visa_Desc.ToString(), obj.Visa_Desc);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(Outbox_Track_Manager_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "Outbox_Track_Manager_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int Outbox_Track_Manager_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "Outbox_Track_Manager_Delete", Outbox_Track_Manager_ID);
                return Outbox_Track_Manager_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "Outbox_Track_Manager_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static Outbox_Track_Manager_DT SelectByID(int Outbox_Track_Manager_ID)
        {
            try
            {
                SqlDataReader drTableName;
                Outbox_Track_Manager_DT oInfo_Outbox_Track_Manager_DT = new Outbox_Track_Manager_DT();
                if (Outbox_Track_Manager_ID > 0)
                {
                    drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "Outbox_Track_Manager_Select", Outbox_Track_Manager_ID);
                    if (drTableName != null)
                    {
                        while (drTableName.Read())
                        {
                            oInfo_Outbox_Track_Manager_DT = FillInfoObject(drTableName);
                        }

                        drTableName.Close();
                    }
                }
                return oInfo_Outbox_Track_Manager_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

