//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\malmeligi using Mcit Generator
// Class Name:		proj_video_service_DT
// Date Generated:	27-06-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class proj_video_service_DT
    {
        public enum Enum_proj_video_service_DT
        {
            proj_video_service_id, proj_id, service_id, File_data, File_name, File_ext, video_header, video_link, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 proj_video_service_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 proj_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 service_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Byte[] File_data;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_ext;
		
		/// <summary>
		/// 
		/// </summary>
		public String video_header;
		
		/// <summary>
		/// 
		/// </summary>
		public String video_link;
		
    }

