//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\malmeligi using Mcit Generator
// Class Name:		proj_img_service_DT
// Date Generated:	26-06-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class proj_img_service_DT
    {
        public enum Enum_proj_img_service_DT
        {
            proj_img_service_id, proj_id, service_id, File_data, File_name, File_ext, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 proj_img_service_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 proj_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 service_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Byte[] File_data;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String File_ext;
		
    }

