//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\malmeligi using Mcit Generator
// Class Name:		proj_services_DT
// Date Generated:	14-05-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class proj_services_DT
    {
        public enum Enum_proj_services_DT
        {
            id, proj_id, proj_citizen_service, proj_gov_service, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 proj_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String proj_citizen_service;
		
		/// <summary>
		/// 
		/// </summary>
		public String proj_gov_service;
		
    }

