//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\Matta using Mcit Generator
// Class Name:		Service_Info_DT
// Date Generated:	26-06-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Service_Info_DT
    {
        public enum Enum_Service_Info_DT
        {
            ID, Service_Type, Project_Id, Hot_Line, Service_Steps, Contact_Us, Project_Location, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int64 ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int64 Service_Type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int64 Project_Id;
		
		/// <summary>
		/// 
		/// </summary>
		public String Hot_Line;
		
		/// <summary>
		/// 
		/// </summary>
		public String Service_Steps;
		
		/// <summary>
		/// 
		/// </summary>
		public String Contact_Us;
		
		/// <summary>
		/// 
		/// </summary>
		public String Project_Location;
		
    }

