//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		Activities_Stages_DT
// Date Generated:	30-01-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Activities_Stages_DT
    {
        public enum Enum_Activities_Stages_DT
        {
            id, Actv_ID, stage_id, proj_id, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 Actv_ID;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 stage_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 proj_id;
		
    }

