//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		Stages_DT
// Date Generated:	30-01-2013
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class Stages_DT
    {
        public enum Enum_Stages_DT
        {
            id, stage_title, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String stage_title;
		
    }

