//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\mmabdelmalek using Mcit Generator
// Class Name:		Admin_Athorization_Select_Module_Page_SP
// Date Generated:	17-10-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;



    public class Admin_Athorization_Select_Module_Page_SP
    {
        public enum Enum_Admin_Athorization_Select_Module_Page_SP
        {
            ModuleID, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 ModuleID;
		

       #region "Private methods"

      
        private static SqlParameter[] GetParameters(Admin_Athorization_Select_Module_Page_SP obj)
        {
            SqlParameter[] parms = new SqlParameter[1];
           
			

        parms[0] = new SqlParameter(Admin_Athorization_Select_Module_Page_SP.Enum_Admin_Athorization_Select_Module_Page_SP.ModuleID.ToString(), obj.ModuleID);
            
            return parms;
        }

        #endregion

       #region "DB methods"

        public static DataTable  Get_DataTable(Admin_Athorization_Select_Module_Page_SP obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

          return SqlHelper.ExecuteDataset(Database.ConnectionString, CommandType.StoredProcedure, "Admin_Athorization_Select_Module_Page", parms).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
        }
     #endregion
    }

